/*
 Hammer.JS - v2.0.7 - 2016-04-22
 http://hammerjs.github.io/

 Copyright (c) 2016 Jorik Tangelder;
 Licensed under the MIT license */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(g,t,p){if(p.get||p.set)throw new TypeError("ES3 does not support getters and setters.");g!=Array.prototype&&g!=Object.prototype&&(g[t]=p.value)};$jscomp.getGlobal=function(g){return"undefined"!=typeof window&&window===g?g:"undefined"!=typeof global&&null!=global?global:g};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(g){return $jscomp.SYMBOL_PREFIX+(g||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var g=$jscomp.global.Symbol.iterator;g||(g=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[g]&&$jscomp.defineProperty(Array.prototype,g,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(g){var t=0;return $jscomp.iteratorPrototype(function(){return t<g.length?{done:!1,value:g[t++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(g){$jscomp.initSymbolIterator();g={next:g};g[$jscomp.global.Symbol.iterator]=function(){return this};return g};$jscomp.makeIterator=function(g){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var t=g[Symbol.iterator];return t?t.call(g):$jscomp.arrayIterator(g)};$jscomp.arrayFromIterator=function(g){for(var t,p=[];!(t=g.next()).done;)p.push(t.value);return p};$jscomp.arrayFromIterable=function(g){return g instanceof Array?g:$jscomp.arrayFromIterator($jscomp.makeIterator(g))};
$jscomp.iteratorFromArray=function(g,t){$jscomp.initSymbolIterator();g instanceof String&&(g+="");var p=0,k={next:function(){if(p<g.length){var B=p++;return{value:t(B,g[B]),done:!1}}k.next=function(){return{done:!0,value:void 0}};return k.next()}};k[Symbol.iterator]=function(){return k};return k};
$jscomp.polyfill=function(g,t,p,k){if(t){p=$jscomp.global;g=g.split(".");for(k=0;k<g.length-1;k++){var B=g[k];B in p||(p[B]={});p=p[B]}g=g[g.length-1];k=p[g];t=t(k);t!=k&&null!=t&&$jscomp.defineProperty(p,g,{configurable:!0,writable:!0,value:t})}};$jscomp.polyfill("Array.prototype.keys",function(g){return g?g:function(){return $jscomp.iteratorFromArray(this,function(g){return g})}},"es6-impl","es3");
$jscomp.polyfill("Array.prototype.entries",function(g){return g?g:function(){return $jscomp.iteratorFromArray(this,function(g,p){return[g,p]})}},"es6-impl","es3");
(function(){var g="undefined"===typeof global?self:global;if("function"!==typeof g.require){var t={},p={},k={},B={}.hasOwnProperty,V=/^\.\.?(\/|$)/,G=function(l,h){var q=[];h=(V.test(h)?l+"/"+h:h).split("/");for(var c=0,a=h.length;c<a;c++)l=h[c],".."===l?q.pop():"."!==l&&""!==l&&q.push(l);return q.join("/")},r=function(l){return function(h){h=G(l.split("/").slice(0,-1).join("/"),h);return g.require(h,l)}},u=function(l){return k[l]?u(k[l]):l},E=function(l,h){return u(G(l.split("/").slice(0,-1).join("/"),
h))},y=function(l,h){null==h&&(h="/");var z=u(l);if(B.call(p,z))return p[z].exports;if(B.call(t,z))return l=t[z],h=q&&q.createHot(z),h={id:z,exports:{},hot:h},p[z]=h,l(h.exports,r(z),h),h.exports;throw Error("Cannot find module '"+l+"' from '"+h+"'");};y.alias=function(l,h){k[h]=l};var x=/\.[^.\/]+$/,z=/\/index(\.[^\/]+)?$/;y.register=y.define=function(l,h){if(l&&"object"===typeof l)for(var q in l)B.call(l,q)&&y.register(q,l[q]);else t[l]=h,delete p[l],x.test(l)&&(h=l.replace(x,""),B.call(k,h)&&k[h].replace(x,
"")!==h+"/index"||(k[h]=l)),z.test(l)&&(h=l.replace(z,""),B.call(k,h)||(k[h]=l))};y.list=function(){var l=[],h;for(h in t)B.call(t,h)&&l.push(h);return l};var q=g._hmr&&new g._hmr(E,y,t,p);y._cache=p;y.hmr=q&&q.wrap;y.brunch=!0;g.require=y}})();
(function(){var g="undefined"===typeof window?this:window,t=function(g,k,B){var p={},G=function(r,u){var k;try{return k=g(u+"/node_modules/"+r)}catch(y){if(-1===y.toString().indexOf("Cannot find module"))throw y;if(-1!==u.indexOf("node_modules"))return u=u.split("/"),k=u.lastIndexOf("node_modules"),u=u.slice(0,k).join("/"),G(r,u)}return p};return function(r){r in k&&(r=k[r]);if(r){if("."!==r[0]&&B){var u=G(r,B);if(u!==p)return u}return g(r)}}};require.register("@fdaciuk/ajax/dist/ajax.min.js",function(g,
k,B){k=t(k,{},"@fdaciuk/ajax");(function(){!function(k,p){"function"==typeof define&&define.amd?define("ajax",p):"object"==typeof g?g=B.exports=p():k.ajax=p()}(this,function(){function g(z,q,l,h){var g=["then","catch","always"].reduce(function(a,d){return a[d]=function(b){return a[d]=b,a},a},{}),c=new XMLHttpRequest;return c.open(z,q,!0),c.withCredentials=h.hasOwnProperty("withCredentials"),k(c,h.headers),c.addEventListener("readystatechange",u(g,c),!1),c.send(y(l)),g.abort=function(){return c.abort()},
g}function k(g,q){q=q||{};r(q)||(q["Content-Type"]="application/x-www-form-urlencoded");Object.keys(q).forEach(function(l){q[l]&&g.setRequestHeader(l,q[l])})}function r(g){return Object.keys(g).some(function(q){return"content-type"===q.toLowerCase()})}function u(g,q){return function h(){q.readyState===q.DONE&&(q.removeEventListener("readystatechange",h,!1),g.always.apply(g,p(q)),200<=q.status&&300>q.status?g.then.apply(g,p(q)):g["catch"].apply(g,p(q)))}}function p(g){var q;try{q=JSON.parse(g.responseText)}catch(l){q=
g.responseText}return[q,g]}function y(g){return"[object Object]"===Object.prototype.toString.call(g)?x(g):g}function x(g){return Object.keys(g).reduce(function(q,l){return(q?q+"\x26":"")+encodeURIComponent(l)+"\x3d"+encodeURIComponent(g[l])},"")}return function(k){var q=["get","post","put","delete"];return k=k||{},k.baseUrl=k.baseUrl||"",k.method&&k.url?g(k.method,k.baseUrl+k.url,k.data||null,k):q.reduce(function(l,h){return l[h]=function(l,c){return g(h,k.baseUrl+l,c||null,k)},l},{})}})})()});require.register("hammerjs/hammer.js",
function(g,k,B){k=t(k,{},"hammerjs");(function(){(function(g,k,r,u){function p(e,a,d){return setTimeout(l(e,d),a)}function y(e,a,d){return Array.isArray(e)?(x(e,d[a],d),!0):!1}function x(e,a,d){var b;if(e)if(e.forEach)e.forEach(a,d);else if(e.length!==u)for(b=0;b<e.length;)a.call(d,e[b],b,e),b++;else for(b in e)e.hasOwnProperty(b)&&a.call(d,e[b],b,e)}function z(e,a,d){var b="DEPRECATED METHOD: "+a+"\n"+d+" AT \n";return function(){var a=Error("get-stack-trace"),a=a&&a.stack?a.stack.replace(/^[^\(]+?[\n$]/gm,
"").replace(/^\s+at\s+/gm,"").replace(/^Object.<anonymous>\s*\(/gm,"{anonymous}()@"):"Unknown Stack Trace",d=g.console&&(g.console.warn||g.console.log);d&&d.call(g.console,b,a);return e.apply(this,arguments)}}function q(e,a,d){a=a.prototype;var b;b=e.prototype=Object.create(a);b.constructor=e;b._super=a;d&&H(b,d)}function l(e,a){return function(){return e.apply(a,arguments)}}function h(e,a){return"function"==typeof e?e.apply(a?a[0]||u:u,a):e}function w(e,a,b){x(d(a),function(a){e.addEventListener(a,
b,!1)})}function c(e,a,b){x(d(a),function(a){e.removeEventListener(a,b,!1)})}function a(e,a){for(;e;){if(e==a)return!0;e=e.parentNode}return!1}function d(e){return e.trim().split(/\s+/g)}function b(e,a,d){if(e.indexOf&&!d)return e.indexOf(a);for(var b=0;b<e.length;){if(d&&e[b][d]==a||!d&&e[b]===a)return b;b++}return-1}function n(e){return Array.prototype.slice.call(e,0)}function f(e,a,d){for(var c=[],C=[],A=0;A<e.length;){var f=a?e[A][a]:e[A];0>b(C,f)&&c.push(e[A]);C[A]=f;A++}d&&(c=a?c.sort(function(e,
d){return e[a]>d[a]}):c.sort());return c}function N(e,a){for(var d,b=a[0].toUpperCase()+a.slice(1),c=0;c<ga.length;){d=(d=ga[c])?d+b:a;if(d in e)return d;c++}return u}function v(e){e=e.ownerDocument||e;return e.defaultView||e.parentWindow||g}function m(e,a){var d=this;this.manager=e;this.callback=a;this.element=e.element;this.target=e.options.inputTarget;this.domHandler=function(a){h(e.options.enable,[e])&&d.handler(a)};this.init()}function ua(e){var a=e.options.inputClass;return new (a?a:va?D:wa?
O:ha?W:G)(e,X)}function X(e,d,b){var c,A,f=b.pointers.length,C=b.changedPointers.length;c=d&1&&0===f-C;b.isFirst=!!c;b.isFinal=!!(d&12&&0===f-C);c&&(e.session={});b.eventType=d;d=e.session;f=b.pointers;C=f.length;d.firstInput||(d.firstInput=ia(b));1<C&&!d.firstMultiple?d.firstMultiple=ia(b):1===C&&(d.firstMultiple=!1);c=d.firstInput;A=(C=d.firstMultiple)?C.center:c.center;var n=b.center=ja(f);b.timeStamp=Y();b.deltaTime=b.timeStamp-c.timeStamp;b.angle=Z(A,n);b.distance=P(A,n);c=b.center;A=d.offsetDelta||
{};var n=d.prevDelta||{},m=d.prevInput||{};if(1===b.eventType||4===m.eventType)n=d.prevDelta={x:m.deltaX||0,y:m.deltaY||0},A=d.offsetDelta={x:c.x,y:c.y};b.deltaX=n.x+(c.x-A.x);b.deltaY=n.y+(c.y-A.y);b.offsetDirection=t(b.deltaX,b.deltaY);A=b.deltaTime;c=b.deltaX/A||0;A=b.deltaY/A||0;b.overallVelocityX=c;b.overallVelocityY=A;b.overallVelocity=L(c)>L(A)?c:A;C?(c=C.pointers,c=P(f[0],f[1],Q)/P(c[0],c[1],Q)):c=1;b.scale=c;C?(C=C.pointers,f=Z(f[1],f[0],Q)+Z(C[1],C[0],Q)):f=0;b.rotation=f;b.maxPointers=
d.prevInput?b.pointers.length>d.prevInput.maxPointers?b.pointers.length:d.prevInput.maxPointers:b.pointers.length;A=d.lastInterval||b;f=b.timeStamp-A.timeStamp;8!=b.eventType&&(25<f||A.velocity===u)?(c=b.deltaX-A.deltaX,A=b.deltaY-A.deltaY,n=c/f||0,m=A/f||0,f=n,C=m,n=L(n)>L(m)?n:m,c=t(c,A),d.lastInterval=b):(n=A.velocity,f=A.velocityX,C=A.velocityY,c=A.direction);b.velocity=n;b.velocityX=f;b.velocityY=C;b.direction=c;d=e.element;a(b.srcEvent.target,d)&&(d=b.srcEvent.target);b.target=d;e.emit("hammer.input",
b);e.recognize(b);e.session.prevInput=b}function ia(e){for(var a=[],b=0;b<e.pointers.length;)a[b]={clientX:M(e.pointers[b].clientX),clientY:M(e.pointers[b].clientY)},b++;return{timeStamp:Y(),pointers:a,center:ja(a),deltaX:e.deltaX,deltaY:e.deltaY}}function ja(e){var a=e.length;if(1===a)return{x:M(e[0].clientX),y:M(e[0].clientY)};for(var b=0,d=0,c=0;c<a;)b+=e[c].clientX,d+=e[c].clientY,c++;return{x:M(b/a),y:M(d/a)}}function t(e,a){return e===a?1:L(e)>=L(a)?0>e?2:4:0>a?8:16}function P(e,a,b){b||(b=
ka);var d=a[b[0]]-e[b[0]];e=a[b[1]]-e[b[1]];return Math.sqrt(d*d+e*e)}function Z(e,a,b){b||(b=ka);return 180*Math.atan2(a[b[1]]-e[b[1]],a[b[0]]-e[b[0]])/Math.PI}function G(){this.evEl=xa;this.evWin=ya;this.pressed=!1;m.apply(this,arguments)}function D(){this.evEl=la;this.evWin=ma;m.apply(this,arguments);this.store=this.manager.session.pointerEvents=[]}function I(){this.evTarget="touchstart";this.evWin="touchstart touchmove touchend touchcancel";this.started=!1;m.apply(this,arguments)}function O(){this.evTarget=
za;this.targetIds={};m.apply(this,arguments)}function V(e,b){var d=n(e.touches),c=this.targetIds;if(b&3&&1===d.length)return c[d[0].identifier]=!0,[d,d];var A;e=n(e.changedTouches);var m=[],g=this.target;A=d.filter(function(e){return a(e.target,g)});if(1===b)for(d=0;d<A.length;)c[A[d].identifier]=!0,d++;for(d=0;d<e.length;)c[e[d].identifier]&&m.push(e[d]),b&12&&delete c[e[d].identifier],d++;if(m.length)return[f(A.concat(m),"identifier",!0),m]}function W(){m.apply(this,arguments);var e=l(this.handler,
this);this.touch=new O(this.manager,e);this.mouse=new G(this.manager,e);this.primaryTouch=null;this.lastTouches=[]}function na(e){e=e.changedPointers[0];if(e.identifier===this.primaryTouch){var a={x:e.clientX,y:e.clientY};this.lastTouches.push(a);var b=this.lastTouches;setTimeout(function(){var e=b.indexOf(a);-1<e&&b.splice(e,1)},2500)}}function aa(e,a){this.manager=e;this.set(a)}function Aa(e){if(-1<e.indexOf("none"))return"none";var a=-1<e.indexOf("pan-x"),b=-1<e.indexOf("pan-y");return a&&b?"none":
a||b?a?"pan-x":"pan-y":-1<e.indexOf("manipulation")?"manipulation":"auto"}function J(e){this.options=H({},this.defaults,e||{});this.id=Ba++;this.manager=null;e=this.options.enable;this.options.enable=e===u?!0:e;this.state=1;this.simultaneous={};this.requireFail=[]}function oa(e){return e&16?"cancel":e&8?"end":e&4?"move":e&2?"start":""}function pa(e){return 16==e?"down":8==e?"up":2==e?"left":4==e?"right":""}function R(e,a){return(a=a.manager)?a.get(e):e}function F(){J.apply(this,arguments)}function S(){F.apply(this,
arguments);this.pY=this.pX=null}function ba(){F.apply(this,arguments)}function ca(){J.apply(this,arguments);this._input=this._timer=null}function da(){F.apply(this,arguments)}function ea(){F.apply(this,arguments)}function T(){J.apply(this,arguments);this.pCenter=this.pTime=!1;this._input=this._timer=null;this.count=0}function K(e,a){a=a||{};var b=a.recognizers;a.recognizers=b===u?K.defaults.preset:b;return new fa(e,a)}function fa(e,a){this.options=H({},K.defaults,a||{});this.options.inputTarget=this.options.inputTarget||
e;this.handlers={};this.session={};this.recognizers=[];this.oldCssProps={};this.element=e;this.input=ua(this);this.touchAction=new aa(this,this.options.touchAction);qa(this,!0);x(this.options.recognizers,function(e){var a=this.add(new e[0](e[1]));e[2]&&a.recognizeWith(e[2]);e[3]&&a.requireFailure(e[3])},this)}function qa(e,a){var b=e.element;if(b.style){var d;x(e.options.cssProps,function(c,f){d=N(b.style,f);a?(e.oldCssProps[d]=b.style[d],b.style[d]=c):b.style[d]=e.oldCssProps[d]||""});a||(e.oldCssProps=
{})}}function Ca(e,a){var b=k.createEvent("Event");b.initEvent(e,!0,!0);b.gesture=a;a.target.dispatchEvent(b)}var ga=" webkit Moz MS ms o".split(" "),Da=k.createElement("div"),M=Math.round,L=Math.abs,Y=Date.now,H;H="function"!==typeof Object.assign?function(e){if(e===u||null===e)throw new TypeError("Cannot convert undefined or null to object");for(var a=Object(e),b=1;b<arguments.length;b++){var d=arguments[b];if(d!==u&&null!==d)for(var c in d)d.hasOwnProperty(c)&&(a[c]=d[c])}return a}:Object.assign;
var ra=z(function(e,a,b){for(var d=Object.keys(a),c=0;c<d.length;){if(!b||b&&e[d[c]]===u)e[d[c]]=a[d[c]];c++}return e},"extend","Use `assign`."),Ea=z(function(e,a){return ra(e,a,!0)},"merge","Use `assign`."),Ba=1,Fa=/mobile|tablet|ip(ad|hone|od)|android/i,ha="ontouchstart"in g,va=N(g,"PointerEvent")!==u,wa=ha&&Fa.test(navigator.userAgent),ka=["x","y"],Q=["clientX","clientY"];m.prototype={handler:function(){},init:function(){this.evEl&&w(this.element,this.evEl,this.domHandler);this.evTarget&&w(this.target,
this.evTarget,this.domHandler);this.evWin&&w(v(this.element),this.evWin,this.domHandler)},destroy:function(){this.evEl&&c(this.element,this.evEl,this.domHandler);this.evTarget&&c(this.target,this.evTarget,this.domHandler);this.evWin&&c(v(this.element),this.evWin,this.domHandler)}};var Ga={mousedown:1,mousemove:2,mouseup:4},xa="mousedown",ya="mousemove mouseup";q(G,m,{handler:function(e){var a=Ga[e.type];a&1&&0===e.button&&(this.pressed=!0);a&2&&1!==e.which&&(a=4);this.pressed&&(a&4&&(this.pressed=
!1),this.callback(this.manager,a,{pointers:[e],changedPointers:[e],pointerType:"mouse",srcEvent:e}))}});var Ha={pointerdown:1,pointermove:2,pointerup:4,pointercancel:8,pointerout:8},Ia={2:"touch",3:"pen",4:"mouse",5:"kinect"},la="pointerdown",ma="pointermove pointerup pointercancel";g.MSPointerEvent&&!g.PointerEvent&&(la="MSPointerDown",ma="MSPointerMove MSPointerUp MSPointerCancel");q(D,m,{handler:function(e){var a=this.store,d=!1,c=e.type.toLowerCase().replace("ms",""),c=Ha[c],f=Ia[e.pointerType]||
e.pointerType,n="touch"==f,m=b(a,e.pointerId,"pointerId");c&1&&(0===e.button||n)?0>m&&(a.push(e),m=a.length-1):c&12&&(d=!0);0>m||(a[m]=e,this.callback(this.manager,c,{pointers:a,changedPointers:[e],pointerType:f,srcEvent:e}),d&&a.splice(m,1))}});var Ja={touchstart:1,touchmove:2,touchend:4,touchcancel:8};q(I,m,{handler:function(a){var e=Ja[a.type];1===e&&(this.started=!0);if(this.started){var b;b=n(a.touches);var d=n(a.changedTouches);e&12&&(b=f(b.concat(d),"identifier",!0));b=[b,d];e&12&&0===b[0].length-
b[1].length&&(this.started=!1);this.callback(this.manager,e,{pointers:b[0],changedPointers:b[1],pointerType:"touch",srcEvent:a})}}});var Ka={touchstart:1,touchmove:2,touchend:4,touchcancel:8},za="touchstart touchmove touchend touchcancel";q(O,m,{handler:function(a){var e=Ka[a.type],b=V.call(this,a,e);b&&this.callback(this.manager,e,{pointers:b[0],changedPointers:b[1],pointerType:"touch",srcEvent:a})}});q(W,m,{handler:function(a,b,d){var e="mouse"==d.pointerType;if(!(e&&d.sourceCapabilities&&d.sourceCapabilities.firesTouchEvents)){if("touch"==
d.pointerType)b&1?(this.primaryTouch=d.changedPointers[0].identifier,na.call(this,d)):b&12&&na.call(this,d);else{if(e)a:{for(var e=d.srcEvent.clientX,c=d.srcEvent.clientY,f=0;f<this.lastTouches.length;f++){var n=this.lastTouches[f],m=Math.abs(c-n.y);if(25>=Math.abs(e-n.x)&&25>=m){e=!0;break a}}e=!1}if(e)return}this.callback(a,b,d)}},destroy:function(){this.touch.destroy();this.mouse.destroy()}});var sa=N(Da.style,"touchAction"),ta=sa!==u,U=function(){if(!ta)return!1;var a={},b=g.CSS&&g.CSS.supports;
"auto;manipulation;pan-y;pan-x;pan-x pan-y;none".split(";").forEach(function(e){a[e]=b?g.CSS.supports("touch-action",e):!0});return a}();aa.prototype={set:function(a){"compute"==a&&(a=this.compute());ta&&this.manager.element.style&&U[a]&&(this.manager.element.style[sa]=a);this.actions=a.toLowerCase().trim()},update:function(){this.set(this.manager.options.touchAction)},compute:function(){var a=[];x(this.manager.recognizers,function(b){h(b.options.enable,[b])&&(a=a.concat(b.getTouchAction()))});return Aa(a.join(" "))},
preventDefaults:function(a){var b=a.srcEvent,e=a.offsetDirection;if(this.manager.session.prevented)b.preventDefault();else{var d=this.actions,c=-1<d.indexOf("none")&&!U.none,f=-1<d.indexOf("pan-y")&&!U["pan-y"],d=-1<d.indexOf("pan-x")&&!U["pan-x"];if(c){var n=2>a.distance,m=250>a.deltaTime;if(1===a.pointers.length&&n&&m)return}if(!d||!f)if(c||f&&e&6||d&&e&24)return this.preventSrc(b)}},preventSrc:function(a){this.manager.session.prevented=!0;a.preventDefault()}};J.prototype={defaults:{},set:function(a){H(this.options,
a);this.manager&&this.manager.touchAction.update();return this},recognizeWith:function(a){if(y(a,"recognizeWith",this))return this;var b=this.simultaneous;a=R(a,this);b[a.id]||(b[a.id]=a,a.recognizeWith(this));return this},dropRecognizeWith:function(a){if(y(a,"dropRecognizeWith",this))return this;a=R(a,this);delete this.simultaneous[a.id];return this},requireFailure:function(a){if(y(a,"requireFailure",this))return this;var d=this.requireFail;a=R(a,this);-1===b(d,a)&&(d.push(a),a.requireFailure(this));
return this},dropRequireFailure:function(a){if(y(a,"dropRequireFailure",this))return this;a=R(a,this);a=b(this.requireFail,a);-1<a&&this.requireFail.splice(a,1);return this},hasRequireFailures:function(){return 0<this.requireFail.length},canRecognizeWith:function(a){return!!this.simultaneous[a.id]},emit:function(a){function b(b){d.manager.emit(b,a)}var d=this,e=this.state;8>e&&b(d.options.event+oa(e));b(d.options.event);a.additionalEvent&&b(a.additionalEvent);8<=e&&b(d.options.event+oa(e))},tryEmit:function(a){if(this.canEmit())return this.emit(a);
this.state=32},canEmit:function(){for(var a=0;a<this.requireFail.length;){if(!(this.requireFail[a].state&33))return!1;a++}return!0},recognize:function(a){a=H({},a);h(this.options.enable,[this,a])?(this.state&56&&(this.state=1),this.state=this.process(a),this.state&30&&this.tryEmit(a)):(this.reset(),this.state=32)},process:function(a){},getTouchAction:function(){},reset:function(){}};q(F,J,{defaults:{pointers:1},attrTest:function(a){var b=this.options.pointers;return 0===b||a.pointers.length===b},
process:function(a){var b=this.state,d=a.eventType,e=b&6;a=this.attrTest(a);return e&&(d&8||!a)?b|16:e||a?d&4?b|8:b&2?b|4:2:32}});q(S,F,{defaults:{event:"pan",threshold:10,pointers:1,direction:30},getTouchAction:function(){var a=this.options.direction,b=[];a&6&&b.push("pan-y");a&24&&b.push("pan-x");return b},directionTest:function(a){var b=this.options,d=!0,e=a.distance,c=a.direction,f=a.deltaX,n=a.deltaY;c&b.direction||(b.direction&6?(c=0===f?1:0>f?2:4,d=f!=this.pX,e=Math.abs(a.deltaX)):(c=0===n?
1:0>n?8:16,d=n!=this.pY,e=Math.abs(a.deltaY)));a.direction=c;return d&&e>b.threshold&&c&b.direction},attrTest:function(a){return F.prototype.attrTest.call(this,a)&&(this.state&2||!(this.state&2)&&this.directionTest(a))},emit:function(a){this.pX=a.deltaX;this.pY=a.deltaY;var b=pa(a.direction);b&&(a.additionalEvent=this.options.event+b);this._super.emit.call(this,a)}});q(ba,F,{defaults:{event:"pinch",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(a){return this._super.attrTest.call(this,
a)&&(Math.abs(a.scale-1)>this.options.threshold||this.state&2)},emit:function(a){1!==a.scale&&(a.additionalEvent=this.options.event+(1>a.scale?"in":"out"));this._super.emit.call(this,a)}});q(ca,J,{defaults:{event:"press",pointers:1,time:251,threshold:9},getTouchAction:function(){return["auto"]},process:function(a){var b=this.options,d=a.pointers.length===b.pointers,c=a.distance<b.threshold,e=a.deltaTime>b.time;this._input=a;if(!c||!d||a.eventType&12&&!e)this.reset();else if(a.eventType&1)this.reset(),
this._timer=p(function(){this.state=8;this.tryEmit()},b.time,this);else if(a.eventType&4)return 8;return 32},reset:function(){clearTimeout(this._timer)},emit:function(a){8===this.state&&(a&&a.eventType&4?this.manager.emit(this.options.event+"up",a):(this._input.timeStamp=Y(),this.manager.emit(this.options.event,this._input)))}});q(da,F,{defaults:{event:"rotate",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(a){return this._super.attrTest.call(this,a)&&(Math.abs(a.rotation)>
this.options.threshold||this.state&2)}});q(ea,F,{defaults:{event:"swipe",threshold:10,velocity:.3,direction:30,pointers:1},getTouchAction:function(){return S.prototype.getTouchAction.call(this)},attrTest:function(a){var b=this.options.direction,d;b&30?d=a.overallVelocity:b&6?d=a.overallVelocityX:b&24&&(d=a.overallVelocityY);return this._super.attrTest.call(this,a)&&b&a.offsetDirection&&a.distance>this.options.threshold&&a.maxPointers==this.options.pointers&&L(d)>this.options.velocity&&a.eventType&
4},emit:function(a){var b=pa(a.offsetDirection);b&&this.manager.emit(this.options.event+b,a);this.manager.emit(this.options.event,a)}});q(T,J,{defaults:{event:"tap",pointers:1,taps:1,interval:300,time:250,threshold:9,posThreshold:10},getTouchAction:function(){return["manipulation"]},process:function(a){var b=this.options,d=a.pointers.length===b.pointers,c=a.distance<b.threshold,e=a.deltaTime<b.time;this.reset();if(a.eventType&1&&0===this.count)return this.failTimeout();if(c&&e&&d){if(4!=a.eventType)return this.failTimeout();
d=this.pTime?a.timeStamp-this.pTime<b.interval:!0;c=!this.pCenter||P(this.pCenter,a.center)<b.posThreshold;this.pTime=a.timeStamp;this.pCenter=a.center;this.count=c&&d?this.count+1:1;this._input=a;if(0===this.count%b.taps)return this.hasRequireFailures()?(this._timer=p(function(){this.state=8;this.tryEmit()},b.interval,this),2):8}return 32},failTimeout:function(){this._timer=p(function(){this.state=32},this.options.interval,this);return 32},reset:function(){clearTimeout(this._timer)},emit:function(){8==
this.state&&(this._input.tapCount=this.count,this.manager.emit(this.options.event,this._input))}});K.VERSION="2.0.7";K.defaults={domEvents:!1,touchAction:"compute",enable:!0,inputTarget:null,inputClass:null,preset:[[da,{enable:!1}],[ba,{enable:!1},["rotate"]],[ea,{direction:6}],[S,{direction:6},["swipe"]],[T],[T,{event:"doubletap",taps:2},["tap"]],[ca]],cssProps:{userSelect:"none",touchSelect:"none",touchCallout:"none",contentZooming:"none",userDrag:"none",tapHighlightColor:"rgba(0,0,0,0)"}};fa.prototype=
{set:function(a){H(this.options,a);a.touchAction&&this.touchAction.update();a.inputTarget&&(this.input.destroy(),this.input.target=a.inputTarget,this.input.init());return this},stop:function(a){this.session.stopped=a?2:1},recognize:function(a){var b=this.session;if(!b.stopped){this.touchAction.preventDefaults(a);var d,c=this.recognizers,e=b.curRecognizer;if(!e||e&&e.state&8)e=b.curRecognizer=null;for(var f=0;f<c.length;)d=c[f],2===b.stopped||e&&d!=e&&!d.canRecognizeWith(e)?d.reset():d.recognize(a),
!e&&d.state&14&&(e=b.curRecognizer=d),f++}},get:function(a){if(a instanceof J)return a;for(var b=this.recognizers,d=0;d<b.length;d++)if(b[d].options.event==a)return b[d];return null},add:function(a){if(y(a,"add",this))return this;var b=this.get(a.options.event);b&&this.remove(b);this.recognizers.push(a);a.manager=this;this.touchAction.update();return a},remove:function(a){if(y(a,"remove",this))return this;if(a=this.get(a)){var d=this.recognizers;a=b(d,a);-1!==a&&(d.splice(a,1),this.touchAction.update())}return this},
on:function(a,b){if(a!==u&&b!==u){var c=this.handlers;x(d(a),function(a){c[a]=c[a]||[];c[a].push(b)});return this}},off:function(a,c){if(a!==u){var e=this.handlers;x(d(a),function(a){c?e[a]&&e[a].splice(b(e[a],c),1):delete e[a]});return this}},emit:function(a,b){this.options.domEvents&&Ca(a,b);var d=this.handlers[a]&&this.handlers[a].slice();if(d&&d.length)for(b.type=a,b.preventDefault=function(){b.srcEvent.preventDefault()},a=0;a<d.length;)d[a](b),a++},destroy:function(){this.element&&qa(this,!1);
this.handlers={};this.session={};this.input.destroy();this.element=null}};H(K,{INPUT_START:1,INPUT_MOVE:2,INPUT_END:4,INPUT_CANCEL:8,STATE_POSSIBLE:1,STATE_BEGAN:2,STATE_CHANGED:4,STATE_ENDED:8,STATE_RECOGNIZED:8,STATE_CANCELLED:16,STATE_FAILED:32,DIRECTION_NONE:1,DIRECTION_LEFT:2,DIRECTION_RIGHT:4,DIRECTION_UP:8,DIRECTION_DOWN:16,DIRECTION_HORIZONTAL:6,DIRECTION_VERTICAL:24,DIRECTION_ALL:30,Manager:fa,Input:m,TouchAction:aa,TouchInput:O,MouseInput:G,PointerEventInput:D,TouchMouseInput:W,SingleTouchInput:I,
Recognizer:J,AttrRecognizer:F,Tap:T,Pan:S,Swipe:ea,Pinch:ba,Rotate:da,Press:ca,on:w,off:c,each:x,merge:Ea,extend:ra,assign:H,inherit:q,bindFn:l,prefixed:N});("undefined"!==typeof g?g:"undefined"!==typeof self?self:{}).Hammer=K;"function"===typeof define&&define.amd?define(function(){return K}):"undefined"!=typeof B&&B.exports?B.exports=K:g[r]=K})(window,document,"Hammer")})()});require.register("marked/lib/marked.js",function(p,k,B){k=t(k,{},"marked");(function(){(function(){function g(c){this.tokens=
[];this.tokens.links={};this.options=c||l.defaults;this.rules=h.normal;this.options.gfm&&(this.rules=this.options.tables?h.tables:h.gfm)}function k(c,a){this.options=a||l.defaults;this.links=c;this.rules=w.normal;this.renderer=this.options.renderer||new r;this.renderer.options=this.options;if(!this.links)throw Error("Tokens array requires a `links` property.");this.options.gfm?this.rules=this.options.breaks?w.breaks:w.gfm:this.options.pedantic&&(this.rules=w.pedantic)}function r(c){this.options=c||
{}}function u(c){this.tokens=[];this.token=null;this.options=c||l.defaults;this.options.renderer=this.options.renderer||new r;this.renderer=this.options.renderer;this.renderer.options=this.options}function t(c,a){return c.replace(a?/&/g:/&(?!#?\w+;)/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/>/g,"\x26gt;").replace(/"/g,"\x26quot;").replace(/'/g,"\x26#39;")}function y(c){return c.replace(/&(#(?:\d+)|(?:#x[0-9A-Fa-f]+)|(?:\w+));?/g,function(a,d){d=d.toLowerCase();return"colon"===d?":":"#"===d.charAt(0)?
"x"===d.charAt(1)?String.fromCharCode(parseInt(d.substring(2),16)):String.fromCharCode(+d.substring(1)):""})}function x(c,a){c=c.source;a=a||"";return function b(n,f){if(!n)return new RegExp(c,a);f=f.source||f;f=f.replace(/(^|[^\[])\^/g,"$1");c=c.replace(n,f);return b}}function z(){}function q(c){for(var a=1,d,b;a<arguments.length;a++)for(b in d=arguments[a],d)Object.prototype.hasOwnProperty.call(d,b)&&(c[b]=d[b]);return c}function l(c,a,d){if(d||"function"===typeof a){d||(d=a,a=null);a=q({},l.defaults,
a||{});var b=a.highlight,n,f,h=0;try{n=g.lex(c,a)}catch(m){return d(m)}f=n.length;var v=function(c){if(c)return a.highlight=b,d(c);var f;try{f=u.parse(n,a)}catch(X){c=X}a.highlight=b;return c?d(c):d(null,f)};if(!b||3>b.length)return v();delete a.highlight;if(!f)return v();for(;h<n.length;h++)(function(a){return"code"!==a.type?--f||v():b(a.text,a.lang,function(b,d){if(b)return v(b);if(null==d||d===a.text)return--f||v();a.text=d;a.escaped=!0;--f||v()})})(n[h])}else try{return a&&(a=q({},l.defaults,
a)),u.parse(g.lex(c,a),a)}catch(m){m.message+="\nPlease report this to https://github.com/chjj/marked.";if((a||l.defaults).silent)return"\x3cp\x3eAn error occured:\x3c/p\x3e\x3cpre\x3e"+t(m.message+"",!0)+"\x3c/pre\x3e";throw m;}}var h={newline:/^\n+/,code:/^( {4}[^\n]+\n*)+/,fences:z,hr:/^( *[-*_]){3,} *(?:\n+|$)/,heading:/^ *(#{1,6}) *([^\n]+?) *#* *(?:\n+|$)/,nptable:z,lheading:/^([^\n]+)\n *(=|-){2,} *(?:\n+|$)/,blockquote:/^( *>[^\n]+(\n(?!def)[^\n]+)*\n*)+/,list:/^( *)(bull) [\s\S]+?(?:hr|def|\n{2,}(?! )(?!\1bull )\n*|\s*$)/,
html:/^ *(?:comment *(?:\n|\s*$)|closed *(?:\n{2,}|\s*$)|closing *(?:\n{2,}|\s*$))/,def:/^ *\[([^\]]+)\]: *<?([^\s>]+)>?(?: +["(]([^\n]+)[")])? *(?:\n+|$)/,table:z,paragraph:/^((?:[^\n]+\n?(?!hr|heading|lheading|blockquote|tag|def))+)\n*/,text:/^[^\n]+/,bullet:/(?:[*+-]|\d+\.)/,item:/^( *)(bull) [^\n]*(?:\n(?!\1bull )[^\n]*)*/};h.item=x(h.item,"gm")(/bull/g,h.bullet)();h.list=x(h.list)(/bull/g,h.bullet)("hr","\\n+(?\x3d\\1?(?:[-*_] *){3,}(?:\\n+|$))")("def","\\n+(?\x3d"+h.def.source+")")();h.blockquote=
x(h.blockquote)("def",h.def)();h._tag="(?!(?:a|em|strong|small|s|cite|q|dfn|abbr|data|time|code|var|samp|kbd|sub|sup|i|b|u|mark|ruby|rt|rp|bdi|bdo|span|br|wbr|ins|del|img)\\b)\\w+(?!:/|[^\\w\\s@]*@)\\b";h.html=x(h.html)("comment",/\x3c!--[\s\S]*?--\x3e/)("closed",/<(tag)[\s\S]+?<\/\1>/)("closing",/<tag(?:"[^"]*"|'[^']*'|[^'">])*?>/)(/tag/g,h._tag)();h.paragraph=x(h.paragraph)("hr",h.hr)("heading",h.heading)("lheading",h.lheading)("blockquote",h.blockquote)("tag","\x3c"+h._tag)("def",h.def)();h.normal=
q({},h);h.gfm=q({},h.normal,{fences:/^ *(`{3,}|~{3,})[ \.]*(\S+)? *\n([\s\S]*?)\s*\1 *(?:\n+|$)/,paragraph:/^/,heading:/^ *(#{1,6}) +([^\n]+?) *#* *(?:\n+|$)/});h.gfm.paragraph=x(h.paragraph)("(?!","(?!"+h.gfm.fences.source.replace("\\1","\\2")+"|"+h.list.source.replace("\\1","\\3")+"|")();h.tables=q({},h.gfm,{nptable:/^ *(\S.*\|.*)\n *([-:]+ *\|[-| :]*)\n((?:.*\|.*(?:\n|$))*)\n*/,table:/^ *\|(.+)\n *\|( *[-:]+[-| :]*)\n((?: *\|.*(?:\n|$))*)\n*/});g.rules=h;g.lex=function(c,a){return(new g(a)).lex(c)};
g.prototype.lex=function(c){c=c.replace(/\r\n|\r/g,"\n").replace(/\t/g,"    ").replace(/\u00a0/g," ").replace(/\u2424/g,"\n");return this.token(c,!0)};g.prototype.token=function(c,a,d){c=c.replace(/^ +$/gm,"");for(var b,n,f,g,v,m,l;c;){if(f=this.rules.newline.exec(c))c=c.substring(f[0].length),1<f[0].length&&this.tokens.push({type:"space"});if(f=this.rules.code.exec(c))c=c.substring(f[0].length),f=f[0].replace(/^ {4}/gm,""),this.tokens.push({type:"code",text:this.options.pedantic?f:f.replace(/\n+$/,
"")});else if(f=this.rules.fences.exec(c))c=c.substring(f[0].length),this.tokens.push({type:"code",lang:f[2],text:f[3]||""});else if(f=this.rules.heading.exec(c))c=c.substring(f[0].length),this.tokens.push({type:"heading",depth:f[1].length,text:f[2]});else if(a&&(f=this.rules.nptable.exec(c))){c=c.substring(f[0].length);v={type:"table",header:f[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:f[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:f[3].replace(/\n$/,"").split("\n")};for(m=0;m<v.align.length;m++)/^ *-+: *$/.test(v.align[m])?
v.align[m]="right":/^ *:-+: *$/.test(v.align[m])?v.align[m]="center":/^ *:-+ *$/.test(v.align[m])?v.align[m]="left":v.align[m]=null;for(m=0;m<v.cells.length;m++)v.cells[m]=v.cells[m].split(/ *\| */);this.tokens.push(v)}else if(f=this.rules.lheading.exec(c))c=c.substring(f[0].length),this.tokens.push({type:"heading",depth:"\x3d"===f[2]?1:2,text:f[1]});else if(f=this.rules.hr.exec(c))c=c.substring(f[0].length),this.tokens.push({type:"hr"});else if(f=this.rules.blockquote.exec(c))c=c.substring(f[0].length),
this.tokens.push({type:"blockquote_start"}),f=f[0].replace(/^ *> ?/gm,""),this.token(f,a,!0),this.tokens.push({type:"blockquote_end"});else if(f=this.rules.list.exec(c)){c=c.substring(f[0].length);g=f[2];this.tokens.push({type:"list_start",ordered:1<g.length});f=f[0].match(this.rules.item);b=!1;l=f.length;for(m=0;m<l;m++)v=f[m],n=v.length,v=v.replace(/^ *([*+-]|\d+\.) +/,""),~v.indexOf("\n ")&&(n-=v.length,v=this.options.pedantic?v.replace(/^ {1,4}/gm,""):v.replace(new RegExp("^ {1,"+n+"}","gm"),
"")),this.options.smartLists&&m!==l-1&&(n=h.bullet.exec(f[m+1])[0],g===n||1<g.length&&1<n.length||(c=f.slice(m+1).join("\n")+c,m=l-1)),n=b||/\n\n(?!\s*$)/.test(v),m!==l-1&&(b="\n"===v.charAt(v.length-1),n||(n=b)),this.tokens.push({type:n?"loose_item_start":"list_item_start"}),this.token(v,!1,d),this.tokens.push({type:"list_item_end"});this.tokens.push({type:"list_end"})}else if(f=this.rules.html.exec(c))c=c.substring(f[0].length),this.tokens.push({type:this.options.sanitize?"paragraph":"html",pre:!this.options.sanitizer&&
("pre"===f[1]||"script"===f[1]||"style"===f[1]),text:f[0]});else if(!d&&a&&(f=this.rules.def.exec(c)))c=c.substring(f[0].length),this.tokens.links[f[1].toLowerCase()]={href:f[2],title:f[3]};else if(a&&(f=this.rules.table.exec(c))){c=c.substring(f[0].length);v={type:"table",header:f[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:f[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:f[3].replace(/(?: *\| *)?\n$/,"").split("\n")};for(m=0;m<v.align.length;m++)/^ *-+: *$/.test(v.align[m])?v.align[m]=
"right":/^ *:-+: *$/.test(v.align[m])?v.align[m]="center":/^ *:-+ *$/.test(v.align[m])?v.align[m]="left":v.align[m]=null;for(m=0;m<v.cells.length;m++)v.cells[m]=v.cells[m].replace(/^ *\| *| *\| *$/g,"").split(/ *\| */);this.tokens.push(v)}else if(a&&(f=this.rules.paragraph.exec(c)))c=c.substring(f[0].length),this.tokens.push({type:"paragraph",text:"\n"===f[1].charAt(f[1].length-1)?f[1].slice(0,-1):f[1]});else if(f=this.rules.text.exec(c))c=c.substring(f[0].length),this.tokens.push({type:"text",text:f[0]});
else if(c)throw Error("Infinite loop on byte: "+c.charCodeAt(0));}return this.tokens};var w={escape:/^\\([\\`*{}\[\]()#+\-.!_>])/,autolink:/^<([^ >]+(@|:\/)[^ >]+)>/,url:z,tag:/^\x3c!--[\s\S]*?--\x3e|^<\/?\w+(?:"[^"]*"|'[^']*'|[^'">])*?>/,link:/^!?\[(inside)\]\(href\)/,reflink:/^!?\[(inside)\]\s*\[([^\]]*)\]/,nolink:/^!?\[((?:\[[^\]]*\]|[^\[\]])*)\]/,strong:/^__([\s\S]+?)__(?!_)|^\*\*([\s\S]+?)\*\*(?!\*)/,em:/^\b_((?:[^_]|__)+?)_\b|^\*((?:\*\*|[\s\S])+?)\*(?!\*)/,code:/^(`+)\s*([\s\S]*?[^`])\s*\1(?!`)/,
br:/^ {2,}\n(?!\s*$)/,del:z,text:/^[\s\S]+?(?=[\\<!\[_*`]| {2,}\n|$)/,_inside:/(?:\[[^\]]*\]|[^\[\]]|\](?=[^\[]*\]))*/,_href:/\s*<?([\s\S]*?)>?(?:\s+['"]([\s\S]*?)['"])?\s*/};w.link=x(w.link)("inside",w._inside)("href",w._href)();w.reflink=x(w.reflink)("inside",w._inside)();w.normal=q({},w);w.pedantic=q({},w.normal,{strong:/^__(?=\S)([\s\S]*?\S)__(?!_)|^\*\*(?=\S)([\s\S]*?\S)\*\*(?!\*)/,em:/^_(?=\S)([\s\S]*?\S)_(?!_)|^\*(?=\S)([\s\S]*?\S)\*(?!\*)/});w.gfm=q({},w.normal,{escape:x(w.escape)("])","~|])")(),
url:/^(https?:\/\/[^\s<]+[^<.,:;"')\]\s])/,del:/^~~(?=\S)([\s\S]*?\S)~~/,text:x(w.text)("]|","~]|")("|","|https?://|")()});w.breaks=q({},w.gfm,{br:x(w.br)("{2,}","*")(),text:x(w.gfm.text)("{2,}","*")()});k.rules=w;k.output=function(c,a,d){return(new k(a,d)).output(c)};k.prototype.output=function(c){for(var a="",d,b;c;)if(b=this.rules.escape.exec(c))c=c.substring(b[0].length),a+=b[1];else if(b=this.rules.autolink.exec(c))c=c.substring(b[0].length),"@"===b[2]?(d=":"===b[1].charAt(6)?this.mangle(b[1].substring(7)):
this.mangle(b[1]),b=this.mangle("mailto:")+d):b=d=t(b[1]),a+=this.renderer.link(b,null,d);else if(!this.inLink&&(b=this.rules.url.exec(c)))c=c.substring(b[0].length),b=d=t(b[1]),a+=this.renderer.link(b,null,d);else if(b=this.rules.tag.exec(c))!this.inLink&&/^<a /i.test(b[0])?this.inLink=!0:this.inLink&&/^<\/a>/i.test(b[0])&&(this.inLink=!1),c=c.substring(b[0].length),a+=this.options.sanitize?this.options.sanitizer?this.options.sanitizer(b[0]):t(b[0]):b[0];else if(b=this.rules.link.exec(c))c=c.substring(b[0].length),
this.inLink=!0,a+=this.outputLink(b,{href:b[2],title:b[3]}),this.inLink=!1;else if((b=this.rules.reflink.exec(c))||(b=this.rules.nolink.exec(c)))c=c.substring(b[0].length),d=(b[2]||b[1]).replace(/\s+/g," "),(d=this.links[d.toLowerCase()])&&d.href?(this.inLink=!0,a+=this.outputLink(b,d),this.inLink=!1):(a+=b[0].charAt(0),c=b[0].substring(1)+c);else if(b=this.rules.strong.exec(c))c=c.substring(b[0].length),a+=this.renderer.strong(this.output(b[2]||b[1]));else if(b=this.rules.em.exec(c))c=c.substring(b[0].length),
a+=this.renderer.em(this.output(b[2]||b[1]));else if(b=this.rules.code.exec(c))c=c.substring(b[0].length),a+=this.renderer.codespan(t(b[2],!0));else if(b=this.rules.br.exec(c))c=c.substring(b[0].length),a+=this.renderer.br();else if(b=this.rules.del.exec(c))c=c.substring(b[0].length),a+=this.renderer.del(this.output(b[1]));else if(b=this.rules.text.exec(c))c=c.substring(b[0].length),a+=this.renderer.text(t(this.smartypants(b[0])));else if(c)throw Error("Infinite loop on byte: "+c.charCodeAt(0));return a};
k.prototype.outputLink=function(c,a){var d=t(a.href);a=a.title?t(a.title):null;return"!"!==c[0].charAt(0)?this.renderer.link(d,a,this.output(c[1])):this.renderer.image(d,a,t(c[1]))};k.prototype.smartypants=function(c){return this.options.smartypants?c.replace(/---/g,"\u2014").replace(/--/g,"\u2013").replace(/(^|[-\u2014/(\[{"\s])'/g,"$1\u2018").replace(/'/g,"\u2019").replace(/(^|[-\u2014/(\[{\u2018\s])"/g,"$1\u201c").replace(/"/g,"\u201d").replace(/\.{3}/g,"\u2026"):c};k.prototype.mangle=function(c){if(!this.options.mangle)return c;
for(var a="",d=c.length,b=0,n;b<d;b++)n=c.charCodeAt(b),.5<Math.random()&&(n="x"+n.toString(16)),a+="\x26#"+n+";";return a};r.prototype.code=function(c,a,d){if(this.options.highlight){var b=this.options.highlight(c,a);null!=b&&b!==c&&(d=!0,c=b)}return a?'\x3cpre\x3e\x3ccode class\x3d"'+this.options.langPrefix+t(a,!0)+'"\x3e'+(d?c:t(c,!0))+"\n\x3c/code\x3e\x3c/pre\x3e\n":"\x3cpre\x3e\x3ccode\x3e"+(d?c:t(c,!0))+"\n\x3c/code\x3e\x3c/pre\x3e"};r.prototype.blockquote=function(c){return"\x3cblockquote\x3e\n"+
c+"\x3c/blockquote\x3e\n"};r.prototype.html=function(c){return c};r.prototype.heading=function(c,a,d){return"\x3ch"+a+' id\x3d"'+this.options.headerPrefix+d.toLowerCase().replace(/[^\w]+/g,"-")+'"\x3e'+c+"\x3c/h"+a+"\x3e\n"};r.prototype.hr=function(){return this.options.xhtml?"\x3chr/\x3e\n":"\x3chr\x3e\n"};r.prototype.list=function(c,a){a=a?"ol":"ul";return"\x3c"+a+"\x3e\n"+c+"\x3c/"+a+"\x3e\n"};r.prototype.listitem=function(c){return"\x3cli\x3e"+c+"\x3c/li\x3e\n"};r.prototype.paragraph=function(c){return"\x3cp\x3e"+
c+"\x3c/p\x3e\n"};r.prototype.table=function(c,a){return"\x3ctable\x3e\n\x3cthead\x3e\n"+c+"\x3c/thead\x3e\n\x3ctbody\x3e\n"+a+"\x3c/tbody\x3e\n\x3c/table\x3e\n"};r.prototype.tablerow=function(c){return"\x3ctr\x3e\n"+c+"\x3c/tr\x3e\n"};r.prototype.tablecell=function(c,a){var d=a.header?"th":"td";return(a.align?"\x3c"+d+' style\x3d"text-align:'+a.align+'"\x3e':"\x3c"+d+"\x3e")+c+"\x3c/"+d+"\x3e\n"};r.prototype.strong=function(c){return"\x3cstrong\x3e"+c+"\x3c/strong\x3e"};r.prototype.em=function(c){return"\x3cem\x3e"+
c+"\x3c/em\x3e"};r.prototype.codespan=function(c){return"\x3ccode\x3e"+c+"\x3c/code\x3e"};r.prototype.br=function(){return this.options.xhtml?"\x3cbr/\x3e":"\x3cbr\x3e"};r.prototype.del=function(c){return"\x3cdel\x3e"+c+"\x3c/del\x3e"};r.prototype.link=function(c,a,d){if(this.options.sanitize){try{var b=decodeURIComponent(y(c)).replace(/[^\w:]/g,"").toLowerCase()}catch(n){return""}if(0===b.indexOf("javascript:")||0===b.indexOf("vbscript:"))return""}c='\x3ca href\x3d"'+c+'"';a&&(c+=' title\x3d"'+a+
'"');return c+("\x3e"+d+"\x3c/a\x3e")};r.prototype.image=function(c,a,d){c='\x3cimg src\x3d"'+c+'" alt\x3d"'+d+'"';a&&(c+=' title\x3d"'+a+'"');return c+=this.options.xhtml?"/\x3e":"\x3e"};r.prototype.text=function(c){return c};u.parse=function(c,a,d){return(new u(a,d)).parse(c)};u.prototype.parse=function(c){this.inline=new k(c.links,this.options,this.renderer);this.tokens=c.reverse();for(c="";this.next();)c+=this.tok();return c};u.prototype.next=function(){return this.token=this.tokens.pop()};u.prototype.peek=
function(){return this.tokens[this.tokens.length-1]||0};u.prototype.parseText=function(){for(var c=this.token.text;"text"===this.peek().type;)c+="\n"+this.next().text;return this.inline.output(c)};u.prototype.tok=function(){switch(this.token.type){case "space":return"";case "hr":return this.renderer.hr();case "heading":return this.renderer.heading(this.inline.output(this.token.text),this.token.depth,this.token.text);case "code":return this.renderer.code(this.token.text,this.token.lang,this.token.escaped);
case "table":var c="",a="",d,b,n,f;n="";for(d=0;d<this.token.header.length;d++)n+=this.renderer.tablecell(this.inline.output(this.token.header[d]),{header:!0,align:this.token.align[d]});c+=this.renderer.tablerow(n);for(d=0;d<this.token.cells.length;d++){b=this.token.cells[d];n="";for(f=0;f<b.length;f++)n+=this.renderer.tablecell(this.inline.output(b[f]),{header:!1,align:this.token.align[f]});a+=this.renderer.tablerow(n)}return this.renderer.table(c,a);case "blockquote_start":for(a="";"blockquote_end"!==
this.next().type;)a+=this.tok();return this.renderer.blockquote(a);case "list_start":a="";for(c=this.token.ordered;"list_end"!==this.next().type;)a+=this.tok();return this.renderer.list(a,c);case "list_item_start":for(a="";"list_item_end"!==this.next().type;)a+="text"===this.token.type?this.parseText():this.tok();return this.renderer.listitem(a);case "loose_item_start":for(a="";"list_item_end"!==this.next().type;)a+=this.tok();return this.renderer.listitem(a);case "html":return a=this.token.pre||
this.options.pedantic?this.token.text:this.inline.output(this.token.text),this.renderer.html(a);case "paragraph":return this.renderer.paragraph(this.inline.output(this.token.text));case "text":return this.renderer.paragraph(this.parseText())}};z.exec=z;l.options=l.setOptions=function(c){q(l.defaults,c);return l};l.defaults={gfm:!0,tables:!0,breaks:!1,pedantic:!1,sanitize:!1,sanitizer:null,mangle:!0,smartLists:!1,silent:!1,highlight:null,langPrefix:"lang-",smartypants:!1,headerPrefix:"",renderer:new r,
xhtml:!1};l.Parser=u;l.parser=u.parse;l.Renderer=r;l.Lexer=g;l.lexer=g.lex;l.InlineLexer=k;l.inlineLexer=k.output;l.parse=l;"undefined"!==typeof B&&"object"===typeof p?B.exports=l:"function"===typeof define&&define.amd?define(function(){return l}):this.marked=l}).call(function(){return this||("undefined"!==typeof window?window:g)}())})()});require.register("components/main.component.svelte",function(g,k,t){function p(a,d){var b,n=document.createElement("div");n.className="MainComp";var f=new q({target:n,
_root:d._root});f.on("mobilemenu",function(a){d.handleMobileMenu(a)});f.on("fontsize",function(a){d.handleFontSize(a)});d.refs.topbar=f;r(document.createTextNode("\n  "),n);var g=new z({target:n,_root:d._root});g.on("mobilemenu",function(a){d.handleMobileMenu(a)});d.refs.menu=g;r(document.createTextNode("\n  "),n);var v=document.createElement("div");n.appendChild(v);v.className="warn";r(document.createTextNode("Disclaimer:"),v);var m=document.createElement("br");v.appendChild(m);r(document.createTextNode("This documentation is a work in progress. It isn't ready and shouldn't be shared with outsiders until the removal of this message. If you want to help build it, please "),
v);m=document.createElement("a");v.appendChild(m);m.href="https://github.com/peercoin/docs#peercoin-official-documentation-repository";r(document.createTextNode("click here"),m);r(document.createTextNode("."),v);r(document.createTextNode("\n  "),n);v=document.createElement("div");n.appendChild(v);v.className="menu-swipper";r(document.createTextNode("\n  "),n);var h=document.createElement("div");n.appendChild(h);h.className=b="doc-container font-"+a.fontSize;var l=c.events.swiperight.call(d,h,function(a){d.handleMobileMenu({action:"OPEN"})});
d.refs.docContainer=h;var k=document.createElement("noscript");h.appendChild(k);var p=document.createElement("noscript");h.appendChild(p);var t=a.documentationHTML;k.insertAdjacentHTML("afterend",t);return{mount:function(a,b){a.insertBefore(n,b)},update:function(a,d){b!==(b="doc-container font-"+d.fontSize)&&(h.className=b);t!==(t=d.documentationHTML)&&(u(k,p),k.insertAdjacentHTML("afterend",t))},unmount:function(){u(k,p);n.parentNode.removeChild(n)},destroy:function(){d.refs.topbar===f&&(d.refs.topbar=
null);f.destroy(!1);d.refs.menu===g&&(d.refs.menu=null);g.destroy(!1);l.teardown();d.refs.docContainer===h&&(d.refs.docContainer=null)}}}function B(a){a=a||{};this.refs={};this._state=E(c.data(),a.data);this._observers={pre:Object.create(null),post:Object.create(null)};this._handlers=Object.create(null);this._root=a._root||this;this._yield=a._yield;this._torndown=!1;this._renderHooks=[];this._fragment=p(this._state,this);a.target&&this._fragment.mount(a.target,null);this._flush();a._root?a._root._renderHooks.push(c.oncreate.bind(this)):
c.oncreate.call(this)}function r(a,d){d.appendChild(a)}function u(a,d){for(;a.nextSibling&&a.nextSibling!==d;)a.parentNode.removeChild(a.nextSibling)}function E(a){for(var d,b,c=1,f=arguments.length;c<f;c++)for(d in b=arguments[c],b)a[d]=b[d];return a}function y(a,d,b,c){for(var f in d)if(f in b){var n=b[f],g=c[f];if(n!==g||n&&"object"===typeof n||"function"===typeof n){var m=d[f];if(m)for(var h=0;h<m.length;h+=1){var l=m[h];l.__calling||(l.__calling=!0,l.call(a,n,g),l.__calling=!1)}}}}var x=k("../herodotus-settings.js"),
z=k("./menu.component"),q=k("./topbar.component"),l=k("marked"),h=k("@fdaciuk/ajax"),w=k("hammerjs"),x=x&&x.__esModule?x["default"]:x,z=z&&z.__esModule?z["default"]:z,q=q&&q.__esModule?q["default"]:q,l=l&&l.__esModule?l["default"]:l,h=h&&h.__esModule?h["default"]:h,w=w&&w.__esModule?w["default"]:w,c=function(){return{oncreate:function(){this.registerDocumentation()},events:{swipeleft:function(a,d){(new w(a)).on("swipeleft",d)},swiperight:function(a,d){(new w(a)).on("swiperight",d)}},data:function(){return{fontSize:2,
documentation:"",documentationHTML:""}},methods:{handleFontSize:function(a){switch(a.action){case "INCREASE":this.increaseFont();break;case "DECREASE":this.decreaseFont()}},handleMobileMenu:function(a){switch(a.action){case "TOGGLE":this.refs.topbar.set({isMenuOpen:this.refs.menu.toggle()});break;case "CLOSE":this.refs.menu.close();this.refs.topbar.set({isMenuOpen:!1});break;case "OPEN":this.refs.menu.open(),this.refs.topbar.set({isMenuOpen:!0})}},increaseFont:function(){var a=this.get("fontSize");
4<=a||this.set({fontSize:a+1})},decreaseFont:function(){var a=this.get("fontSize");1>=a||this.set({fontSize:a-1})},registerDocumentation:function(){var a=this,d;d=x.allow_remote_documentation?x.remote_documentation_url:"documentation.md";h().get(d).then(function(b,d){a.set({documentation:b,documentationHTML:l(b)});a.refs.menu.startMenu(a.generateMenu())})},generateMenu:function(){var a=[],d=[],b;this.refs.docContainer.querySelectorAll("h1, h2").forEach(function(c){d.push({type:c.nodeName.toLowerCase(),
label:c.textContent,id:c.id});"h1"===c.nodeName.toLowerCase()?(a.push({type:c.nodeName.toLowerCase(),label:c.textContent,id:c.id}),b=a[a.length-1],b.children=[]):"h2"===c.nodeName.toLowerCase()&&b.children.push({type:c.nodeName.toLowerCase(),label:c.textContent,id:c.id})});return{menuItems:a,menuItemsFlat:d}}}}}();E(B.prototype,c.methods,{get:function(a){return a?this._state[a]:this._state},fire:function(a,d){if(a=a in this._handlers&&this._handlers[a].slice())for(var b=0;b<a.length;b+=1)a[b].call(this,
d)},observe:function(a,d,b){var c=b&&b.defer?this._observers.post:this._observers.pre;(c[a]||(c[a]=[])).push(d);b&&!1===b.init||(d.__calling=!0,d.call(this,this._state[a]),d.__calling=!1);return{cancel:function(){var b=c[a].indexOf(d);~b&&c[a].splice(b,1)}}},on:function(a,d){if("teardown"===a)return this.on("destroy",d);var b=this._handlers[a]||(this._handlers[a]=[]);b.push(d);return{cancel:function(){var a=b.indexOf(d);~a&&b.splice(a,1)}}},set:function(a){this._set(E({},a));this._root._flush()},
_flush:function(){if(this._renderHooks)for(;this._renderHooks.length;)this._renderHooks.pop()()}});B.prototype._set=function(a){var d=this._state;this._state=E({},d,a);y(this,this._observers.pre,a,d);this._fragment.update(a,this._state);y(this,this._observers.post,a,d);this._flush()};B.prototype.teardown=B.prototype.destroy=function(a){this.fire("destroy");!1!==a&&this._fragment.unmount();this._fragment.destroy();this._fragment=null;this._state={};this._torndown=!0};t.exports=B});require.register("components/menu.component.svelte",
function(g,k,t){function p(d,b){function c(a){b.onAppScroll(this.scrollY)}function f(a){b.fire("mobilemenu",{action:"CLOSE"})}function g(a){b.scrollTop()}var h,m;window.addEventListener("scroll",c);var k=document.createTextNode("\n"),p=document.createElement("div"),u=document.createElement("div");p.appendChild(u);u.className=h="MenuComp--overlay "+(d.isOpen?"active":"");u.addEventListener("click",f,!1);b.refs.overlay=u;q(document.createTextNode("\n  "),p);var t=document.createElement("div");p.appendChild(t);
t.className=m="MenuComp "+(d.isOpen?"open":"");var r=a.events.swipeleft.call(b,t,function(a){b.fire("mobilemenu",{action:"CLOSE"})});b.refs.menu=t;var w=document.createElement("div");t.appendChild(w);w.className="logo";w.addEventListener("click",g,!1);var x=document.createElement("img");w.appendChild(x);x.src="img/logo.svg";x.alt="PeerAssets WhitePaper";q(document.createTextNode("\n    "),t);var y=document.createElement("ul");t.appendChild(y);y.className="menu";for(var x=d.menuItems,D=[],I=0;I<x.length;I+=
1)D[I]=B(d,x,x[I],I,b),D[I].mount(y,null);return{mount:function(a,b){a.insertBefore(k,b);a.insertBefore(p,b)},update:function(a,d){h!==(h="MenuComp--overlay "+(d.isOpen?"active":""))&&(u.className=h);m!==(m="MenuComp "+(d.isOpen?"open":""))&&(t.className=m);var c=d.menuItems;if("menuItems"in a){for(var f=0;f<c.length;f+=1)D[f]?D[f].update(a,d,c,c[f],f):(D[f]=B(d,c,c[f],f,b),D[f].mount(y,null));for(;f<D.length;f+=1)D[f].unmount(),D[f].destroy();D.length=c.length}},unmount:function(){z(k);z(p);for(var a=
0;a<D.length;a+=1)D[a].unmount()},destroy:function(){window.removeEventListener("scroll",c);u.removeEventListener("click",f,!1);b.refs.overlay===u&&(b.refs.overlay=null);r.teardown();b.refs.menu===t&&(b.refs.menu=null);w.removeEventListener("click",g,!1);l(D,!1,0)}}}function B(a,b,c,f,g){var d,n,h,l,k=document.createElement("li");k.id=d="menu-"+c.id;k.className=n=c.type;var p=document.createElement("a");k.appendChild(p);p.href=h="#"+c.id;p.addEventListener("click",E,!1);p._svelte={component:g,each_block_value:b,
item_index:f};var t=document.createTextNode(l=c.label);p.appendChild(t);q(document.createTextNode("\n            "),k);var r=0<c.children.length&&u(a,b,c,f,g);r&&r.mount(k,null);return{mount:function(a,b){a.insertBefore(k,b)},update:function(a,b,c,f,m){d!==(d="menu-"+f.id)&&(k.id=d);n!==(n=f.type)&&(k.className=n);h!==(h="#"+f.id)&&(p.href=h);p._svelte.each_block_value=c;p._svelte.item_index=m;l!==(l=f.label)&&(t.data=l);0<f.children.length?r?r.update(a,b,c,f,m):(r=u(b,c,f,m,g),r.mount(k,null)):r&&
(r.unmount(),r.destroy(),r=null)},unmount:function(){z(k);r&&r.unmount()},destroy:function(){p.removeEventListener("click",E,!1);r&&r.destroy()}}}function r(a,b,c,f,g,h,m,l){var d,n,k,v,q=document.createElement("li");q.id=d="menu-"+h.id;q.className=n=h.type;var p=document.createElement("a");q.appendChild(p);p.href=k="#"+h.id;p.addEventListener("click",y,!1);p._svelte={component:l,each_block_value_1:g,subitem_index:m};var r=document.createTextNode(v=h.label);p.appendChild(r);return{mount:function(a,
b){a.insertBefore(q,b)},update:function(a,b,c,f,g,h,m,l){d!==(d="menu-"+m.id)&&(q.id=d);n!==(n=m.type)&&(q.className=n);k!==(k="#"+m.id)&&(p.href=k);p._svelte.each_block_value_1=h;p._svelte.subitem_index=l;v!==(v=m.label)&&(r.data=v)},unmount:function(){z(q)},destroy:function(){p.removeEventListener("click",y,!1)}}}function u(a,b,c,f,g){var d=document.createElement("ul");d.className="subsection";for(var n=c.children,h=[],k=0;k<n.length;k+=1)h[k]=r(a,b,c,f,n,n[k],k,g),h[k].mount(d,null);return{mount:function(a,
b){a.insertBefore(d,b)},update:function(a,b,c,f,n){var m=f.children;if("menuItems"in a){for(var k=0;k<m.length;k+=1)h[k]?h[k].update(a,b,c,f,n,m,m[k],k):(h[k]=r(b,c,f,n,m,m[k],k,g),h[k].mount(d,null));for(;k<h.length;k+=1)h[k].unmount(),h[k].destroy();h.length=m.length}},unmount:function(){z(d);for(var a=0;a<h.length;a+=1)h[a].unmount()},destroy:function(){l(h,!1,0)}}}function E(a){this._svelte.component.scrollToItem(this._svelte.each_block_value[this._svelte.item_index],a)}function y(a){this._svelte.component.scrollToItem(this._svelte.each_block_value_1[this._svelte.subitem_index],
a)}function x(d){d=d||{};this.refs={};this._state=h(a.data(),d.data);this._observers={pre:Object.create(null),post:Object.create(null)};this._handlers=Object.create(null);this._root=d._root||this;this._yield=d._yield;this._torndown=!1;this._fragment=p(this._state,this);d.target&&this._fragment.mount(d.target,null);d._root?d._root._renderHooks.push(a.oncreate.bind(this)):a.oncreate.call(this)}function z(a){a.parentNode.removeChild(a)}function q(a,b){b.appendChild(a)}function l(a,b,c){for(;c<a.length;c+=
1)a[c]&&a[c].destroy(b)}function h(a){for(var b,d,c=1,g=arguments.length;c<g;c++)for(b in d=arguments[c],d)a[b]=d[b];return a}function w(a,b,c,f){for(var d in b)if(d in c){var g=c[d],h=f[d];if(g!==h||g&&"object"===typeof g||"function"===typeof g){var n=b[d];if(n)for(var k=0;k<n.length;k+=1){var l=n[k];l.__calling||(l.__calling=!0,l.call(a,g,h),l.__calling=!1)}}}}var c=k("hammerjs"),c=c&&c.__esModule?c["default"]:c,a=function(){return{oncreate:function(){console.log(c)},events:{swipeleft:function(a,
b){(new c(a)).on("swipeleft",b)},swiperight:function(a,b){(new c(a)).on("swiperight",b)}},data:function(){return{menuItems:[],menuItemsFlat:[],isOpen:!1,prevY:0}},methods:{onAppScroll:function(a){a=this.get("menuItemsFlat");a=$jscomp.makeIterator(a.entries());for(var b=a.next();!b.done;b=a.next()){b=$jscomp.makeIterator(b.value);b.next();var b=b.next().value,d=document.getElementById(b.id),c=d.getBoundingClientRect().top,d=d.getBoundingClientRect().bottom;if(0<=c&&d<=window.innerHeight){[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu li.active"))).map(function(a){return a.classList.remove("active")});
a=document.getElementById("menu-"+b.id);a.classList.add("active");b=a.parentNode;b.classList.contains("subsection")&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),b.classList.add("show"));0<a.querySelectorAll(".subsection").length&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),a.querySelector(".subsection").classList.add("show"));
break}}},startMenu:function(a){var b=this;this.set(a);setTimeout(function(){b.scrollToURLMenu()},10)},scrollTop:function(){window.scrollTo(0,0);this.close()},scrollToURLMenu:function(){var a=window.location.hash.substr(2),b=this.get("menuItemsFlat").filter(function(b){return b.id===a});0<b.length?(b=document.getElementById(b[0].id),b=window.scrollY+b.getBoundingClientRect().top-70,window.scrollTo(0,b)):window.scrollTo(0,1)},toggle:function(){this.set({isOpen:!this.refs.menu.isOpen});return this.refs.menu.isOpen},
close:function(){this.set({isOpen:!1})},open:function(){this.set({isOpen:!0})},scrollToItem:function(a,b){b&&b.preventDefault();window.location.hash="/"+a.id;this.get("menuItemsFlat");a=window.scrollY+document.getElementById(a.id).getBoundingClientRect().top-70;window.scrollTo(0,a);this.fire("mobilemenu",{action:"CLOSE"})}}}}();h(x.prototype,a.methods,{get:function(a){return a?this._state[a]:this._state},fire:function(a,b){if(a=a in this._handlers&&this._handlers[a].slice())for(var d=0;d<a.length;d+=
1)a[d].call(this,b)},observe:function(a,b,c){var d=c&&c.defer?this._observers.post:this._observers.pre;(d[a]||(d[a]=[])).push(b);c&&!1===c.init||(b.__calling=!0,b.call(this,this._state[a]),b.__calling=!1);return{cancel:function(){var c=d[a].indexOf(b);~c&&d[a].splice(c,1)}}},on:function(a,b){if("teardown"===a)return this.on("destroy",b);var d=this._handlers[a]||(this._handlers[a]=[]);d.push(b);return{cancel:function(){var a=d.indexOf(b);~a&&d.splice(a,1)}}},set:function(a){this._set(h({},a));this._root._flush()},
_flush:function(){if(this._renderHooks)for(;this._renderHooks.length;)this._renderHooks.pop()()}});x.prototype._set=function(a){var b=this._state;this._state=h({},b,a);w(this,this._observers.pre,a,b);this._fragment.update(a,this._state);w(this,this._observers.post,a,b)};x.prototype.teardown=x.prototype.destroy=function(a){this.fire("destroy");!1!==a&&this._fragment.unmount();this._fragment.destroy();this._fragment=null;this._state={};this._torndown=!0};t.exports=x});require.register("components/topbar.component.svelte",
function(g,k,t){function p(a,d){function b(a){d.fire("mobilemenu",{action:"TOGGLE"})}var c,f=document.createElement("div");f.className="TopbarComp";var g=document.createElement("div");f.appendChild(g);g.className="menu-button";g.addEventListener("click",b,!1);var h=y("svg");g.appendChild(h);x(h,"class",c="svg-icon "+(a.isMenuOpen?"off":""));h.setAttribute("xmlns","http://www.w3.org/2000/svg");h.setAttribute("role","img");h.setAttribute("viewBox","0 0 40 28");var k=y("use");h.appendChild(k);z(k,"xlink:href",
"img/icon-menu-open.svg#icon");k.setAttribute("preserveAspectRatio","xMidYMid");E(document.createTextNode("\n\n    "),f);var l=a.settings.allow_font_size_control&&B(a,d);l&&l.mount(f,null);var q=document.createTextNode("\n\n    ");f.appendChild(q);var p=a.settings.allow_topbar_link&&r(a,d);p&&p.mount(f,null);return{mount:function(a,b){a.insertBefore(f,b)},update:function(a,b){c!==(c="svg-icon "+(b.isMenuOpen?"off":""))&&h.setAttribute("class",c);b.settings.allow_font_size_control?l||(l=B(b,d),l.mount(f,
q)):l&&(l.unmount(),l.destroy(),l=null);b.settings.allow_topbar_link?p?p.update(a,b):(p=r(b,d),p.mount(f,null)):p&&(p.unmount(),p.destroy(),p=null)},unmount:function(){f.parentNode.removeChild(f);l&&l.unmount();p&&p.unmount()},destroy:function(){g.removeEventListener("click",b,!1);l&&l.destroy();p&&p.destroy()}}}function B(a,c){function b(a){c.fire("fontsize",{action:"DECREASE"})}function d(a){c.fire("fontsize",{action:"INCREASE"})}var f=document.createElement("div");f.className="btn-group";var g=
document.createElement("div");f.appendChild(g);g.className="btn btn-svg v-center";g.addEventListener("click",b,!1);a=y("svg");g.appendChild(a);a.setAttribute("class","svg-icon");a.setAttribute("xmlns","http://www.w3.org/2000/svg");a.setAttribute("role","img");a.setAttribute("viewBox","0 0 26 20");var h=y("use");a.appendChild(h);z(h,"xlink:href","img/icon-font-minus.svg#icon");h.setAttribute("preserveAspectRatio","xMidYMid");E(document.createTextNode("\n      "),f);var k=document.createElement("div");
f.appendChild(k);k.className="btn btn-svg v-center";k.addEventListener("click",d,!1);a=y("svg");k.appendChild(a);a.setAttribute("class","svg-icon");a.setAttribute("xmlns","http://www.w3.org/2000/svg");a.setAttribute("role","img");a.setAttribute("viewBox","0 0 26 20");h=y("use");a.appendChild(h);z(h,"xlink:href","img/icon-font-plus.svg#icon");h.setAttribute("preserveAspectRatio","xMidYMid");return{mount:function(a,b){a.insertBefore(f,b)},unmount:function(){f.parentNode.removeChild(f)},destroy:function(){g.removeEventListener("click",
b,!1);k.removeEventListener("click",d,!1)}}}function r(a,c){var b,d,f=document.createElement("a");f.href=b=a.settings.topbar_link_url;f.className="btn btn-last-link";var g=document.createTextNode(d=a.settings.topbar_link_label);f.appendChild(g);return{mount:function(a,b){a.insertBefore(f,b)},update:function(a,c){b!==(b=c.settings.topbar_link_url)&&(f.href=b);d!==(d=c.settings.topbar_link_label)&&(g.data=d)},unmount:function(){f.parentNode.removeChild(f)},destroy:h}}function u(a){a=a||{};this._state=
q(c.data(),a.data);this._observers={pre:Object.create(null),post:Object.create(null)};this._handlers=Object.create(null);this._root=a._root||this;this._yield=a._yield;this._torndown=!1;this._fragment=p(this._state,this);a.target&&this._fragment.mount(a.target,null)}function E(a,c){c.appendChild(a)}function y(a){return document.createElementNS("http://www.w3.org/2000/svg",a)}function x(a,c,b){a.setAttribute(c,b)}function z(a,c,b){a.setAttributeNS("http://www.w3.org/1999/xlink",c,b)}function q(a){for(var c,
b,g=1,f=arguments.length;g<f;g++)for(c in b=arguments[g],b)a[c]=b[c];return a}function l(a,c,b,g){for(var d in c)if(d in b){var h=b[d],k=g[d];if(h!==k||h&&"object"===typeof h||"function"===typeof h){var l=c[d];if(l)for(var n=0;n<l.length;n+=1){var p=l[n];p.__calling||(p.__calling=!0,p.call(a,h,k),p.__calling=!1)}}}}function h(){}var w=k("../herodotus-settings.js"),w=w&&w.__esModule?w["default"]:w,c=function(){return{data:function(){return{settings:w}}}}();q(u.prototype,{get:function(a){return a?this._state[a]:
this._state},fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var b=0;b<a.length;b+=1)a[b].call(this,c)},observe:function(a,c,b){var d=b&&b.defer?this._observers.post:this._observers.pre;(d[a]||(d[a]=[])).push(c);b&&!1===b.init||(c.__calling=!0,c.call(this,this._state[a]),c.__calling=!1);return{cancel:function(){var b=d[a].indexOf(c);~b&&d[a].splice(b,1)}}},on:function(a,c){if("teardown"===a)return this.on("destroy",c);var b=this._handlers[a]||(this._handlers[a]=[]);b.push(c);
return{cancel:function(){var a=b.indexOf(c);~a&&b.splice(a,1)}}},set:function(a){this._set(q({},a));this._root._flush()},_flush:function(){if(this._renderHooks)for(;this._renderHooks.length;)this._renderHooks.pop()()}});u.prototype._set=function(a){var c=this._state;this._state=q({},c,a);l(this,this._observers.pre,a,c);this._fragment.update(a,this._state);l(this,this._observers.post,a,c)};u.prototype.teardown=u.prototype.destroy=function(a){this.fire("destroy");!1!==a&&this._fragment.unmount();this._fragment.destroy();
this._fragment=null;this._state={};this._torndown=!0};t.exports=u});require.register("herodotus-settings.js",function(g,k,t){Object.defineProperty(g,"__esModule",{value:!0});g.default={documentation_name:"My awesome documentation",allow_topbar_link:!0,topbar_link_label:"Contribute to Peercoin Docs",topbar_link_url:"https://github.com/peercoin/docs#peercoin-official-documentation-repository",allow_font_size_control:!0,allow_remote_documentation:!1,remote_documentation_url:""}});require.register("initialize.js",
function(g,k,t){var p=(g=k("./components/main.component"))&&g.__esModule?g:{default:g};document.addEventListener("DOMContentLoaded",function(){window.mainComponent=new p.default({target:document.querySelector("main")})})});require.alias("@fdaciuk/ajax/dist/ajax.min.js","@fdaciuk/ajax");require.alias("hammerjs/hammer.js","hammerjs");require.alias("marked/lib/marked.js","marked");require.register("___globals___",function(g,k,t){})})();require("___globals___");require("initialize");