var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,p,l){if(l.get||l.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[p]=l.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var p=0;return $jscomp.iteratorPrototype(function(){return p<c.length?{done:!1,value:c[p++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.makeIterator=function(c){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var p=c[Symbol.iterator];return p?p.call(c):$jscomp.arrayIterator(c)};$jscomp.arrayFromIterator=function(c){for(var p,l=[];!(p=c.next()).done;)l.push(p.value);return l};$jscomp.arrayFromIterable=function(c){return c instanceof Array?c:$jscomp.arrayFromIterator($jscomp.makeIterator(c))};
$jscomp.iteratorFromArray=function(c,p){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var l=0,e={next:function(){if(l<c.length){var w=l++;return{value:p(w,c[w]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(c,p,l,e){if(p){l=$jscomp.global;c=c.split(".");for(e=0;e<c.length-1;e++){var w=c[e];w in l||(l[w]={});l=l[w]}c=c[c.length-1];e=l[c];p=p(e);p!=e&&null!=p&&$jscomp.defineProperty(l,c,{configurable:!0,writable:!0,value:p})}};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6-impl","es3");
$jscomp.polyfill("Array.prototype.entries",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(c,l){return[c,l]})}},"es6-impl","es3");
(function(){var c="undefined"===typeof global?self:global;if("function"!==typeof c.require){var p={},l={},e={},w={}.hasOwnProperty,E=/^\.\.?(\/|$)/,D=function(h,f){var c=[];f=(E.test(f)?h+"/"+f:f).split("/");for(var a=0,b=f.length;a<b;a++)h=f[a],".."===h?c.pop():"."!==h&&""!==h&&c.push(h);return c.join("/")},m=function(h){return function(f){f=D(h.split("/").slice(0,-1).join("/"),f);return c.require(f,h)}},y=function(h){return e[h]?y(e[h]):h},v=function(h,f){return y(D(h.split("/").slice(0,-1).join("/"),
f))},z=function(h,f){null==f&&(f="/");var c=y(h);if(w.call(l,c))return l[c].exports;if(w.call(p,c))return h=p[c],f=q&&q.createHot(c),f={id:c,exports:{},hot:f},l[c]=f,h(f.exports,m(c),f),f.exports;throw Error("Cannot find module '"+h+"' from '"+f+"'");};z.alias=function(h,f){e[f]=h};var t=/\.[^.\/]+$/,x=/\/index(\.[^\/]+)?$/;z.register=z.define=function(h,f){if(h&&"object"===typeof h)for(var c in h)w.call(h,c)&&z.register(c,h[c]);else p[h]=f,delete l[h],t.test(h)&&(f=h.replace(t,""),w.call(e,f)&&e[f].replace(t,
"")!==f+"/index"||(e[f]=h)),x.test(h)&&(f=h.replace(x,""),w.call(e,f)||(e[f]=h))};z.list=function(){var h=[],f;for(f in p)w.call(p,f)&&h.push(f);return h};var q=c._hmr&&new c._hmr(v,z,p,l);z._cache=l;z.hmr=q&&q.wrap;z.brunch=!0;c.require=z}})();
(function(){var c="undefined"===typeof window?this:window,p=function(c,e,w){var l={},D=function(m,e){var v;try{return v=c(e+"/node_modules/"+m)}catch(z){if(-1===z.toString().indexOf("Cannot find module"))throw z;if(-1!==e.indexOf("node_modules"))return e=e.split("/"),v=e.lastIndexOf("node_modules"),e=e.slice(0,v).join("/"),D(m,e)}return l};return function(m){m in e&&(m=e[m]);if(m){if("."!==m[0]&&w){var y=D(m,w);if(y!==l)return y}return c(m)}}};require.register("@fdaciuk/ajax/dist/ajax.min.js",function(c,
e,w){e=p(e,{},"@fdaciuk/ajax");(function(){!function(e,l){"function"==typeof define&&define.amd?define("ajax",l):"object"==typeof c?c=w.exports=l():e.ajax=l()}(this,function(){function c(c,q,h,f){var x=["then","catch","always"].reduce(function(b,a){return b[a]=function(d){return b[a]=d,b},b},{}),a=new XMLHttpRequest;return a.open(c,q,!0),a.withCredentials=f.hasOwnProperty("withCredentials"),e(a,f.headers),a.addEventListener("readystatechange",l(x,a),!1),a.send(w(h)),x.abort=function(){return a.abort()},
x}function e(c,q){q=q||{};m(q)||(q["Content-Type"]="application/x-www-form-urlencoded");Object.keys(q).forEach(function(h){q[h]&&c.setRequestHeader(h,q[h])})}function m(c){return Object.keys(c).some(function(c){return"content-type"===c.toLowerCase()})}function l(c,q){return function f(){q.readyState===q.DONE&&(q.removeEventListener("readystatechange",f,!1),c.always.apply(c,v(q)),200<=q.status&&300>q.status?c.then.apply(c,v(q)):c["catch"].apply(c,v(q)))}}function v(c){var q;try{q=JSON.parse(c.responseText)}catch(h){q=
c.responseText}return[q,c]}function w(c){return"[object Object]"===Object.prototype.toString.call(c)?t(c):c}function t(c){return Object.keys(c).reduce(function(q,h){return(q?q+"\x26":"")+encodeURIComponent(h)+"\x3d"+encodeURIComponent(c[h])},"")}return function(e){var q=["get","post","put","delete"];return e=e||{},e.baseUrl=e.baseUrl||"",e.method&&e.url?c(e.method,e.baseUrl+e.url,e.data||null,e):q.reduce(function(h,f){return h[f]=function(h,a){return c(f,e.baseUrl+h,a||null,e)},h},{})}})})()});require.register("marked/lib/marked.js",
function(l,e,w){e=p(e,{},"marked");(function(){(function(){function c(a){this.tokens=[];this.tokens.links={};this.options=a||h.defaults;this.rules=f.normal;this.options.gfm&&(this.rules=this.options.tables?f.tables:f.gfm)}function e(a,b){this.options=b||h.defaults;this.links=a;this.rules=u.normal;this.renderer=this.options.renderer||new m;this.renderer.options=this.options;if(!this.links)throw Error("Tokens array requires a `links` property.");this.options.gfm?this.rules=this.options.breaks?u.breaks:
u.gfm:this.options.pedantic&&(this.rules=u.pedantic)}function m(a){this.options=a||{}}function y(a){this.tokens=[];this.token=null;this.options=a||h.defaults;this.options.renderer=this.options.renderer||new m;this.renderer=this.options.renderer;this.renderer.options=this.options}function v(a,b){return a.replace(b?/&/g:/&(?!#?\w+;)/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/>/g,"\x26gt;").replace(/"/g,"\x26quot;").replace(/'/g,"\x26#39;")}function p(a){return a.replace(/&(#(?:\d+)|(?:#x[0-9A-Fa-f]+)|(?:\w+));?/g,
function(b,a){a=a.toLowerCase();return"colon"===a?":":"#"===a.charAt(0)?"x"===a.charAt(1)?String.fromCharCode(parseInt(a.substring(2),16)):String.fromCharCode(+a.substring(1)):""})}function t(a,b){a=a.source;b=b||"";return function d(c,k){if(!c)return new RegExp(a,b);k=k.source||k;k=k.replace(/(^|[^\[])\^/g,"$1");a=a.replace(c,k);return d}}function x(){}function q(a){for(var b=1,g,d;b<arguments.length;b++)for(d in g=arguments[b],g)Object.prototype.hasOwnProperty.call(g,d)&&(a[d]=g[d]);return a}function h(a,
b,g){if(g||"function"===typeof b){g||(g=b,b=null);b=q({},h.defaults,b||{});var d=b.highlight,f,k,e=0;try{f=c.lex(a,b)}catch(n){return g(n)}k=f.length;var r=function(a){if(a)return b.highlight=d,g(a);var k;try{k=y.parse(f,b)}catch(F){a=F}b.highlight=d;return a?g(a):g(null,k)};if(!d||3>d.length)return r();delete b.highlight;if(!k)return r();for(;e<f.length;e++)(function(b){return"code"!==b.type?--k||r():d(b.text,b.lang,function(a,d){if(a)return r(a);if(null==d||d===b.text)return--k||r();b.text=d;b.escaped=
!0;--k||r()})})(f[e])}else try{return b&&(b=q({},h.defaults,b)),y.parse(c.lex(a,b),b)}catch(n){n.message+="\nPlease report this to https://github.com/chjj/marked.";if((b||h.defaults).silent)return"\x3cp\x3eAn error occured:\x3c/p\x3e\x3cpre\x3e"+v(n.message+"",!0)+"\x3c/pre\x3e";throw n;}}var f={newline:/^\n+/,code:/^( {4}[^\n]+\n*)+/,fences:x,hr:/^( *[-*_]){3,} *(?:\n+|$)/,heading:/^ *(#{1,6}) *([^\n]+?) *#* *(?:\n+|$)/,nptable:x,lheading:/^([^\n]+)\n *(=|-){2,} *(?:\n+|$)/,blockquote:/^( *>[^\n]+(\n(?!def)[^\n]+)*\n*)+/,
list:/^( *)(bull) [\s\S]+?(?:hr|def|\n{2,}(?! )(?!\1bull )\n*|\s*$)/,html:/^ *(?:comment *(?:\n|\s*$)|closed *(?:\n{2,}|\s*$)|closing *(?:\n{2,}|\s*$))/,def:/^ *\[([^\]]+)\]: *<?([^\s>]+)>?(?: +["(]([^\n]+)[")])? *(?:\n+|$)/,table:x,paragraph:/^((?:[^\n]+\n?(?!hr|heading|lheading|blockquote|tag|def))+)\n*/,text:/^[^\n]+/,bullet:/(?:[*+-]|\d+\.)/,item:/^( *)(bull) [^\n]*(?:\n(?!\1bull )[^\n]*)*/};f.item=t(f.item,"gm")(/bull/g,f.bullet)();f.list=t(f.list)(/bull/g,f.bullet)("hr","\\n+(?\x3d\\1?(?:[-*_] *){3,}(?:\\n+|$))")("def",
"\\n+(?\x3d"+f.def.source+")")();f.blockquote=t(f.blockquote)("def",f.def)();f._tag="(?!(?:a|em|strong|small|s|cite|q|dfn|abbr|data|time|code|var|samp|kbd|sub|sup|i|b|u|mark|ruby|rt|rp|bdi|bdo|span|br|wbr|ins|del|img)\\b)\\w+(?!:/|[^\\w\\s@]*@)\\b";f.html=t(f.html)("comment",/\x3c!--[\s\S]*?--\x3e/)("closed",/<(tag)[\s\S]+?<\/\1>/)("closing",/<tag(?:"[^"]*"|'[^']*'|[^'">])*?>/)(/tag/g,f._tag)();f.paragraph=t(f.paragraph)("hr",f.hr)("heading",f.heading)("lheading",f.lheading)("blockquote",f.blockquote)("tag",
"\x3c"+f._tag)("def",f.def)();f.normal=q({},f);f.gfm=q({},f.normal,{fences:/^ *(`{3,}|~{3,})[ \.]*(\S+)? *\n([\s\S]*?)\s*\1 *(?:\n+|$)/,paragraph:/^/,heading:/^ *(#{1,6}) +([^\n]+?) *#* *(?:\n+|$)/});f.gfm.paragraph=t(f.paragraph)("(?!","(?!"+f.gfm.fences.source.replace("\\1","\\2")+"|"+f.list.source.replace("\\1","\\3")+"|")();f.tables=q({},f.gfm,{nptable:/^ *(\S.*\|.*)\n *([-:]+ *\|[-| :]*)\n((?:.*\|.*(?:\n|$))*)\n*/,table:/^ *\|(.+)\n *\|( *[-:]+[-| :]*)\n((?: *\|.*(?:\n|$))*)\n*/});c.rules=f;
c.lex=function(a,b){return(new c(b)).lex(a)};c.prototype.lex=function(a){a=a.replace(/\r\n|\r/g,"\n").replace(/\t/g,"    ").replace(/\u00a0/g," ").replace(/\u2424/g,"\n");return this.token(a,!0)};c.prototype.token=function(a,b,g){a=a.replace(/^ +$/gm,"");for(var d,c,k,h,r,n,e;a;){if(k=this.rules.newline.exec(a))a=a.substring(k[0].length),1<k[0].length&&this.tokens.push({type:"space"});if(k=this.rules.code.exec(a))a=a.substring(k[0].length),k=k[0].replace(/^ {4}/gm,""),this.tokens.push({type:"code",
text:this.options.pedantic?k:k.replace(/\n+$/,"")});else if(k=this.rules.fences.exec(a))a=a.substring(k[0].length),this.tokens.push({type:"code",lang:k[2],text:k[3]||""});else if(k=this.rules.heading.exec(a))a=a.substring(k[0].length),this.tokens.push({type:"heading",depth:k[1].length,text:k[2]});else if(b&&(k=this.rules.nptable.exec(a))){a=a.substring(k[0].length);r={type:"table",header:k[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:k[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:k[3].replace(/\n$/,
"").split("\n")};for(n=0;n<r.align.length;n++)/^ *-+: *$/.test(r.align[n])?r.align[n]="right":/^ *:-+: *$/.test(r.align[n])?r.align[n]="center":/^ *:-+ *$/.test(r.align[n])?r.align[n]="left":r.align[n]=null;for(n=0;n<r.cells.length;n++)r.cells[n]=r.cells[n].split(/ *\| */);this.tokens.push(r)}else if(k=this.rules.lheading.exec(a))a=a.substring(k[0].length),this.tokens.push({type:"heading",depth:"\x3d"===k[2]?1:2,text:k[1]});else if(k=this.rules.hr.exec(a))a=a.substring(k[0].length),this.tokens.push({type:"hr"});
else if(k=this.rules.blockquote.exec(a))a=a.substring(k[0].length),this.tokens.push({type:"blockquote_start"}),k=k[0].replace(/^ *> ?/gm,""),this.token(k,b,!0),this.tokens.push({type:"blockquote_end"});else if(k=this.rules.list.exec(a)){a=a.substring(k[0].length);h=k[2];this.tokens.push({type:"list_start",ordered:1<h.length});k=k[0].match(this.rules.item);d=!1;e=k.length;for(n=0;n<e;n++)r=k[n],c=r.length,r=r.replace(/^ *([*+-]|\d+\.) +/,""),~r.indexOf("\n ")&&(c-=r.length,r=this.options.pedantic?
r.replace(/^ {1,4}/gm,""):r.replace(new RegExp("^ {1,"+c+"}","gm"),"")),this.options.smartLists&&n!==e-1&&(c=f.bullet.exec(k[n+1])[0],h===c||1<h.length&&1<c.length||(a=k.slice(n+1).join("\n")+a,n=e-1)),c=d||/\n\n(?!\s*$)/.test(r),n!==e-1&&(d="\n"===r.charAt(r.length-1),c||(c=d)),this.tokens.push({type:c?"loose_item_start":"list_item_start"}),this.token(r,!1,g),this.tokens.push({type:"list_item_end"});this.tokens.push({type:"list_end"})}else if(k=this.rules.html.exec(a))a=a.substring(k[0].length),
this.tokens.push({type:this.options.sanitize?"paragraph":"html",pre:!this.options.sanitizer&&("pre"===k[1]||"script"===k[1]||"style"===k[1]),text:k[0]});else if(!g&&b&&(k=this.rules.def.exec(a)))a=a.substring(k[0].length),this.tokens.links[k[1].toLowerCase()]={href:k[2],title:k[3]};else if(b&&(k=this.rules.table.exec(a))){a=a.substring(k[0].length);r={type:"table",header:k[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:k[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:k[3].replace(/(?: *\| *)?\n$/,
"").split("\n")};for(n=0;n<r.align.length;n++)/^ *-+: *$/.test(r.align[n])?r.align[n]="right":/^ *:-+: *$/.test(r.align[n])?r.align[n]="center":/^ *:-+ *$/.test(r.align[n])?r.align[n]="left":r.align[n]=null;for(n=0;n<r.cells.length;n++)r.cells[n]=r.cells[n].replace(/^ *\| *| *\| *$/g,"").split(/ *\| */);this.tokens.push(r)}else if(b&&(k=this.rules.paragraph.exec(a)))a=a.substring(k[0].length),this.tokens.push({type:"paragraph",text:"\n"===k[1].charAt(k[1].length-1)?k[1].slice(0,-1):k[1]});else if(k=
this.rules.text.exec(a))a=a.substring(k[0].length),this.tokens.push({type:"text",text:k[0]});else if(a)throw Error("Infinite loop on byte: "+a.charCodeAt(0));}return this.tokens};var u={escape:/^\\([\\`*{}\[\]()#+\-.!_>])/,autolink:/^<([^ >]+(@|:\/)[^ >]+)>/,url:x,tag:/^\x3c!--[\s\S]*?--\x3e|^<\/?\w+(?:"[^"]*"|'[^']*'|[^'">])*?>/,link:/^!?\[(inside)\]\(href\)/,reflink:/^!?\[(inside)\]\s*\[([^\]]*)\]/,nolink:/^!?\[((?:\[[^\]]*\]|[^\[\]])*)\]/,strong:/^__([\s\S]+?)__(?!_)|^\*\*([\s\S]+?)\*\*(?!\*)/,
em:/^\b_((?:[^_]|__)+?)_\b|^\*((?:\*\*|[\s\S])+?)\*(?!\*)/,code:/^(`+)\s*([\s\S]*?[^`])\s*\1(?!`)/,br:/^ {2,}\n(?!\s*$)/,del:x,text:/^[\s\S]+?(?=[\\<!\[_*`]| {2,}\n|$)/,_inside:/(?:\[[^\]]*\]|[^\[\]]|\](?=[^\[]*\]))*/,_href:/\s*<?([\s\S]*?)>?(?:\s+['"]([\s\S]*?)['"])?\s*/};u.link=t(u.link)("inside",u._inside)("href",u._href)();u.reflink=t(u.reflink)("inside",u._inside)();u.normal=q({},u);u.pedantic=q({},u.normal,{strong:/^__(?=\S)([\s\S]*?\S)__(?!_)|^\*\*(?=\S)([\s\S]*?\S)\*\*(?!\*)/,em:/^_(?=\S)([\s\S]*?\S)_(?!_)|^\*(?=\S)([\s\S]*?\S)\*(?!\*)/});
u.gfm=q({},u.normal,{escape:t(u.escape)("])","~|])")(),url:/^(https?:\/\/[^\s<]+[^<.,:;"')\]\s])/,del:/^~~(?=\S)([\s\S]*?\S)~~/,text:t(u.text)("]|","~]|")("|","|https?://|")()});u.breaks=q({},u.gfm,{br:t(u.br)("{2,}","*")(),text:t(u.gfm.text)("{2,}","*")()});e.rules=u;e.output=function(a,b,g){return(new e(b,g)).output(a)};e.prototype.output=function(a){for(var b="",g,d;a;)if(d=this.rules.escape.exec(a))a=a.substring(d[0].length),b+=d[1];else if(d=this.rules.autolink.exec(a))a=a.substring(d[0].length),
"@"===d[2]?(g=":"===d[1].charAt(6)?this.mangle(d[1].substring(7)):this.mangle(d[1]),d=this.mangle("mailto:")+g):d=g=v(d[1]),b+=this.renderer.link(d,null,g);else if(!this.inLink&&(d=this.rules.url.exec(a)))a=a.substring(d[0].length),d=g=v(d[1]),b+=this.renderer.link(d,null,g);else if(d=this.rules.tag.exec(a))!this.inLink&&/^<a /i.test(d[0])?this.inLink=!0:this.inLink&&/^<\/a>/i.test(d[0])&&(this.inLink=!1),a=a.substring(d[0].length),b+=this.options.sanitize?this.options.sanitizer?this.options.sanitizer(d[0]):
v(d[0]):d[0];else if(d=this.rules.link.exec(a))a=a.substring(d[0].length),this.inLink=!0,b+=this.outputLink(d,{href:d[2],title:d[3]}),this.inLink=!1;else if((d=this.rules.reflink.exec(a))||(d=this.rules.nolink.exec(a)))a=a.substring(d[0].length),g=(d[2]||d[1]).replace(/\s+/g," "),(g=this.links[g.toLowerCase()])&&g.href?(this.inLink=!0,b+=this.outputLink(d,g),this.inLink=!1):(b+=d[0].charAt(0),a=d[0].substring(1)+a);else if(d=this.rules.strong.exec(a))a=a.substring(d[0].length),b+=this.renderer.strong(this.output(d[2]||
d[1]));else if(d=this.rules.em.exec(a))a=a.substring(d[0].length),b+=this.renderer.em(this.output(d[2]||d[1]));else if(d=this.rules.code.exec(a))a=a.substring(d[0].length),b+=this.renderer.codespan(v(d[2],!0));else if(d=this.rules.br.exec(a))a=a.substring(d[0].length),b+=this.renderer.br();else if(d=this.rules.del.exec(a))a=a.substring(d[0].length),b+=this.renderer.del(this.output(d[1]));else if(d=this.rules.text.exec(a))a=a.substring(d[0].length),b+=this.renderer.text(v(this.smartypants(d[0])));
else if(a)throw Error("Infinite loop on byte: "+a.charCodeAt(0));return b};e.prototype.outputLink=function(a,b){var g=v(b.href);b=b.title?v(b.title):null;return"!"!==a[0].charAt(0)?this.renderer.link(g,b,this.output(a[1])):this.renderer.image(g,b,v(a[1]))};e.prototype.smartypants=function(a){return this.options.smartypants?a.replace(/---/g,"\u2014").replace(/--/g,"\u2013").replace(/(^|[-\u2014/(\[{"\s])'/g,"$1\u2018").replace(/'/g,"\u2019").replace(/(^|[-\u2014/(\[{\u2018\s])"/g,"$1\u201c").replace(/"/g,
"\u201d").replace(/\.{3}/g,"\u2026"):a};e.prototype.mangle=function(a){if(!this.options.mangle)return a;for(var b="",g=a.length,d=0,c;d<g;d++)c=a.charCodeAt(d),.5<Math.random()&&(c="x"+c.toString(16)),b+="\x26#"+c+";";return b};m.prototype.code=function(a,b,g){if(this.options.highlight){var d=this.options.highlight(a,b);null!=d&&d!==a&&(g=!0,a=d)}return b?'\x3cpre\x3e\x3ccode class\x3d"'+this.options.langPrefix+v(b,!0)+'"\x3e'+(g?a:v(a,!0))+"\n\x3c/code\x3e\x3c/pre\x3e\n":"\x3cpre\x3e\x3ccode\x3e"+
(g?a:v(a,!0))+"\n\x3c/code\x3e\x3c/pre\x3e"};m.prototype.blockquote=function(a){return"\x3cblockquote\x3e\n"+a+"\x3c/blockquote\x3e\n"};m.prototype.html=function(a){return a};m.prototype.heading=function(a,b,g){return"\x3ch"+b+' id\x3d"'+this.options.headerPrefix+g.toLowerCase().replace(/[^\w]+/g,"-")+'"\x3e'+a+"\x3c/h"+b+"\x3e\n"};m.prototype.hr=function(){return this.options.xhtml?"\x3chr/\x3e\n":"\x3chr\x3e\n"};m.prototype.list=function(a,b){b=b?"ol":"ul";return"\x3c"+b+"\x3e\n"+a+"\x3c/"+b+"\x3e\n"};
m.prototype.listitem=function(a){return"\x3cli\x3e"+a+"\x3c/li\x3e\n"};m.prototype.paragraph=function(a){return"\x3cp\x3e"+a+"\x3c/p\x3e\n"};m.prototype.table=function(a,b){return"\x3ctable\x3e\n\x3cthead\x3e\n"+a+"\x3c/thead\x3e\n\x3ctbody\x3e\n"+b+"\x3c/tbody\x3e\n\x3c/table\x3e\n"};m.prototype.tablerow=function(a){return"\x3ctr\x3e\n"+a+"\x3c/tr\x3e\n"};m.prototype.tablecell=function(a,b){var g=b.header?"th":"td";return(b.align?"\x3c"+g+' style\x3d"text-align:'+b.align+'"\x3e':"\x3c"+g+"\x3e")+
a+"\x3c/"+g+"\x3e\n"};m.prototype.strong=function(a){return"\x3cstrong\x3e"+a+"\x3c/strong\x3e"};m.prototype.em=function(a){return"\x3cem\x3e"+a+"\x3c/em\x3e"};m.prototype.codespan=function(a){return"\x3ccode\x3e"+a+"\x3c/code\x3e"};m.prototype.br=function(){return this.options.xhtml?"\x3cbr/\x3e":"\x3cbr\x3e"};m.prototype.del=function(a){return"\x3cdel\x3e"+a+"\x3c/del\x3e"};m.prototype.link=function(a,b,g){if(this.options.sanitize){try{var d=decodeURIComponent(p(a)).replace(/[^\w:]/g,"").toLowerCase()}catch(A){return""}if(0===
d.indexOf("javascript:")||0===d.indexOf("vbscript:"))return""}a='\x3ca href\x3d"'+a+'"';b&&(a+=' title\x3d"'+b+'"');return a+("\x3e"+g+"\x3c/a\x3e")};m.prototype.image=function(a,b,g){a='\x3cimg src\x3d"'+a+'" alt\x3d"'+g+'"';b&&(a+=' title\x3d"'+b+'"');return a+=this.options.xhtml?"/\x3e":"\x3e"};m.prototype.text=function(a){return a};y.parse=function(a,b,g){return(new y(b,g)).parse(a)};y.prototype.parse=function(a){this.inline=new e(a.links,this.options,this.renderer);this.tokens=a.reverse();for(a=
"";this.next();)a+=this.tok();return a};y.prototype.next=function(){return this.token=this.tokens.pop()};y.prototype.peek=function(){return this.tokens[this.tokens.length-1]||0};y.prototype.parseText=function(){for(var a=this.token.text;"text"===this.peek().type;)a+="\n"+this.next().text;return this.inline.output(a)};y.prototype.tok=function(){switch(this.token.type){case "space":return"";case "hr":return this.renderer.hr();case "heading":return this.renderer.heading(this.inline.output(this.token.text),
this.token.depth,this.token.text);case "code":return this.renderer.code(this.token.text,this.token.lang,this.token.escaped);case "table":var a="",b="",g,d,c,k;c="";for(g=0;g<this.token.header.length;g++)c+=this.renderer.tablecell(this.inline.output(this.token.header[g]),{header:!0,align:this.token.align[g]});a+=this.renderer.tablerow(c);for(g=0;g<this.token.cells.length;g++){d=this.token.cells[g];c="";for(k=0;k<d.length;k++)c+=this.renderer.tablecell(this.inline.output(d[k]),{header:!1,align:this.token.align[k]});
b+=this.renderer.tablerow(c)}return this.renderer.table(a,b);case "blockquote_start":for(b="";"blockquote_end"!==this.next().type;)b+=this.tok();return this.renderer.blockquote(b);case "list_start":b="";for(a=this.token.ordered;"list_end"!==this.next().type;)b+=this.tok();return this.renderer.list(b,a);case "list_item_start":for(b="";"list_item_end"!==this.next().type;)b+="text"===this.token.type?this.parseText():this.tok();return this.renderer.listitem(b);case "loose_item_start":for(b="";"list_item_end"!==
this.next().type;)b+=this.tok();return this.renderer.listitem(b);case "html":return b=this.token.pre||this.options.pedantic?this.token.text:this.inline.output(this.token.text),this.renderer.html(b);case "paragraph":return this.renderer.paragraph(this.inline.output(this.token.text));case "text":return this.renderer.paragraph(this.parseText())}};x.exec=x;h.options=h.setOptions=function(a){q(h.defaults,a);return h};h.defaults={gfm:!0,tables:!0,breaks:!1,pedantic:!1,sanitize:!1,sanitizer:null,mangle:!0,
smartLists:!1,silent:!1,highlight:null,langPrefix:"lang-",smartypants:!1,headerPrefix:"",renderer:new m,xhtml:!1};h.Parser=y;h.parser=y.parse;h.Renderer=m;h.Lexer=c;h.lexer=c.lex;h.InlineLexer=e;h.inlineLexer=e.output;h.parse=h;"undefined"!==typeof w&&"object"===typeof l?w.exports=h:"function"===typeof define&&define.amd?define(function(){return h}):this.marked=h}).call(function(){return this||("undefined"!==typeof window?window:c)}())})()});require.register("components/main.component.svelte",function(c,
e,w){function l(a,b){var g,d=document.createElement("div");d.className="MainComp";var c=new q({target:d,_root:b._root});c.on("mobilemenu",function(a){b.handleMobileMenu(a)});c.on("fontsize",function(a){b.handleFontSize(a)});b.refs.topbar=c;m(document.createTextNode("\n  "),d);var k=new x({target:d,_root:b._root});k.on("mobilemenu",function(a){b.handleMobileMenu(a)});b.refs.menu=k;m(document.createTextNode("\n  "),d);var f=document.createElement("div");d.appendChild(f);f.className="warn";m(document.createTextNode("Disclaimer:"),
f);var r=document.createElement("br");f.appendChild(r);m(document.createTextNode("This documentation is a work in progress. It isn't ready and shouldn't be shared with outsiders until the removal of this message. If you want to help build it, please "),f);r=document.createElement("a");f.appendChild(r);r.href="https://github.com/peercoin/docs#peercoin-official-documentation-repository";m(document.createTextNode("click here"),r);m(document.createTextNode("."),f);m(document.createTextNode("\n  "),d);
var n=document.createElement("div");d.appendChild(n);n.className=g="doc-container font-"+a.fontSize;b.refs.docContainer=n;var h=document.createElement("noscript");n.appendChild(h);var e=document.createElement("noscript");n.appendChild(e);var l=a.documentationHTML;h.insertAdjacentHTML("afterend",l);return{mount:function(b,a){b.insertBefore(d,a)},update:function(b,a){g!==(g="doc-container font-"+a.fontSize)&&(n.className=g);l!==(l=a.documentationHTML)&&(y(h,e),h.insertAdjacentHTML("afterend",l))},unmount:function(){y(h,
e);d.parentNode.removeChild(d)},destroy:function(){b.refs.topbar===c&&(b.refs.topbar=null);c.destroy(!1);b.refs.menu===k&&(b.refs.menu=null);k.destroy(!1);b.refs.docContainer===n&&(b.refs.docContainer=null)}}}function p(a){a=a||{};this.refs={};this._state=v(u.data(),a.data);this._observers={pre:Object.create(null),post:Object.create(null)};this._handlers=Object.create(null);this._root=a._root||this;this._yield=a._yield;this._torndown=!1;this._renderHooks=[];this._fragment=l(this._state,this);a.target&&
this._fragment.mount(a.target,null);this._flush();a._root?a._root._renderHooks.push(u.oncreate.bind(this)):u.oncreate.call(this)}function m(a,b){b.appendChild(a)}function y(a,b){for(;a.nextSibling&&a.nextSibling!==b;)a.parentNode.removeChild(a.nextSibling)}function v(a){for(var b,g,d=1,c=arguments.length;d<c;d++)for(b in g=arguments[d],g)a[b]=g[b];return a}function z(a,b,g,d){for(var c in b)if(c in g){var k=g[c],f=d[c];if(k!==f||k&&"object"===typeof k||"function"===typeof k){var h=b[c];if(h)for(var n=
0;n<h.length;n+=1){var e=h[n];e.__calling||(e.__calling=!0,e.call(a,k,f),e.__calling=!1)}}}}var t=e("../herodotus-settings.js"),x=e("./menu.component"),q=e("./topbar.component"),h=e("marked"),f=e("@fdaciuk/ajax"),t=t&&t.__esModule?t["default"]:t,x=x&&x.__esModule?x["default"]:x,q=q&&q.__esModule?q["default"]:q,h=h&&h.__esModule?h["default"]:h,f=f&&f.__esModule?f["default"]:f,u=function(){return{oncreate:function(){this.registerDocumentation()},data:function(){return{fontSize:2,documentation:"",documentationHTML:""}},
methods:{handleFontSize:function(a){switch(a.action){case "INCREASE":this.increaseFont();break;case "DECREASE":this.decreaseFont()}},handleMobileMenu:function(a){switch(a.action){case "TOGGLE":this.refs.topbar.set({isMenuOpen:this.refs.menu.toggle()});break;case "CLOSE":this.refs.menu.close();break;case "OPEN":this.refs.menu.open(),this.refs.topbar.set({isMenuOpen:!0})}},increaseFont:function(){var a=this.get("fontSize");4<=a||this.set({fontSize:a+1})},decreaseFont:function(){var a=this.get("fontSize");
1>=a||this.set({fontSize:a-1})},registerDocumentation:function(){var a=this,b;b=t.allow_remote_documentation?t.remote_documentation_url:"documentation.md";f().get(b).then(function(b,d){a.set({documentation:b,documentationHTML:h(b)});a.refs.menu.startMenu(a.generateMenu())})},generateMenu:function(){var a=[],b=[],g;this.refs.docContainer.querySelectorAll("h1, h2").forEach(function(d){b.push({type:d.nodeName.toLowerCase(),label:d.textContent,id:d.id});"h1"===d.nodeName.toLowerCase()?(a.push({type:d.nodeName.toLowerCase(),
label:d.textContent,id:d.id}),g=a[a.length-1],g.children=[]):"h2"===d.nodeName.toLowerCase()&&g.children.push({type:d.nodeName.toLowerCase(),label:d.textContent,id:d.id})});return{menuItems:a,menuItemsFlat:b}}}}}();v(p.prototype,u.methods,{get:function(a){return a?this._state[a]:this._state},fire:function(a,b){if(a=a in this._handlers&&this._handlers[a].slice())for(var g=0;g<a.length;g+=1)a[g].call(this,b)},observe:function(a,b,g){var d=g&&g.defer?this._observers.post:this._observers.pre;(d[a]||(d[a]=
[])).push(b);g&&!1===g.init||(b.__calling=!0,b.call(this,this._state[a]),b.__calling=!1);return{cancel:function(){var g=d[a].indexOf(b);~g&&d[a].splice(g,1)}}},on:function(a,b){if("teardown"===a)return this.on("destroy",b);var g=this._handlers[a]||(this._handlers[a]=[]);g.push(b);return{cancel:function(){var a=g.indexOf(b);~a&&g.splice(a,1)}}},set:function(a){this._set(v({},a));this._root._flush()},_flush:function(){if(this._renderHooks)for(;this._renderHooks.length;)this._renderHooks.pop()()}});
p.prototype._set=function(a){var b=this._state;this._state=v({},b,a);z(this,this._observers.pre,a,b);this._fragment.update(a,this._state);z(this,this._observers.post,a,b);this._flush()};p.prototype.teardown=p.prototype.destroy=function(a){this.fire("destroy");!1!==a&&this._fragment.unmount();this._fragment.destroy();this._fragment=null;this._state={};this._torndown=!0};w.exports=p});require.register("components/menu.component.svelte",function(c,e,p){function l(b,a){function d(b){a.onAppScroll(this.scrollY)}
function g(b){a.fire("mobilemenu",{action:"CLOSE"})}function c(b){a.scrollTop()}var f,e;window.addEventListener("scroll",d);var n=document.createTextNode("\n"),l=document.createElement("div"),m=document.createElement("div");l.appendChild(m);m.className=f="MenuComp--overlay "+(b.isOpen?"active":"");m.addEventListener("click",g,!1);a.refs.overlay=m;q(document.createTextNode("\n  "),l);var B=document.createElement("div");l.appendChild(B);B.className=e="MenuComp "+(b.isOpen?"open":"");a.refs.menu=B;var p=
document.createElement("div");B.appendChild(p);p.className="logo";p.addEventListener("click",c,!1);var C=document.createElement("img");p.appendChild(C);C.src="img/logo.svg";C.alt="PeerAssets WhitePaper";q(document.createTextNode("\n    "),B);var u=document.createElement("ul");B.appendChild(u);u.className="menu";for(var C=b.menuItems,t=[],v=0;v<C.length;v+=1)t[v]=w(b,C,C[v],v,a),t[v].mount(u,null);return{mount:function(a,b){a.insertBefore(n,b);a.insertBefore(l,b)},update:function(b,d){f!==(f="MenuComp--overlay "+
(d.isOpen?"active":""))&&(m.className=f);e!==(e="MenuComp "+(d.isOpen?"open":""))&&(B.className=e);var g=d.menuItems;if("menuItems"in b){for(var c=0;c<g.length;c+=1)t[c]?t[c].update(b,d,g,g[c],c):(t[c]=w(d,g,g[c],c,a),t[c].mount(u,null));for(;c<t.length;c+=1)t[c].unmount(),t[c].destroy();t.length=g.length}},unmount:function(){x(n);x(l);for(var b=0;b<t.length;b+=1)t[b].unmount()},destroy:function(){window.removeEventListener("scroll",d);m.removeEventListener("click",g,!1);a.refs.overlay===m&&(a.refs.overlay=
null);a.refs.menu===B&&(a.refs.menu=null);p.removeEventListener("click",c,!1);h(t,!1,0)}}}function w(b,a,d,c,k){var g,f,e,h,l=document.createElement("li");l.id=g="menu-"+d.id;l.className=f=d.type;var m=document.createElement("a");l.appendChild(m);m.href=e="#"+d.id;m.addEventListener("click",v,!1);m._svelte={component:k,each_block_value:a,item_index:c};var t=document.createTextNode(h=d.label);m.appendChild(t);q(document.createTextNode("\n            "),l);var A=0<d.children.length&&y(b,a,d,c,k);A&&
A.mount(l,null);return{mount:function(b,a){b.insertBefore(l,a)},update:function(b,a,d,c,n){g!==(g="menu-"+c.id)&&(l.id=g);f!==(f=c.type)&&(l.className=f);e!==(e="#"+c.id)&&(m.href=e);m._svelte.each_block_value=d;m._svelte.item_index=n;h!==(h=c.label)&&(t.data=h);0<c.children.length?A?A.update(b,a,d,c,n):(A=y(a,d,c,n,k),A.mount(l,null)):A&&(A.unmount(),A.destroy(),A=null)},unmount:function(){x(l);A&&A.unmount()},destroy:function(){m.removeEventListener("click",v,!1);A&&A.destroy()}}}function m(b,a,
d,c,k,f,e,h){var g,n,r,l,m=document.createElement("li");m.id=g="menu-"+f.id;m.className=n=f.type;var A=document.createElement("a");m.appendChild(A);A.href=r="#"+f.id;A.addEventListener("click",z,!1);A._svelte={component:h,each_block_value_1:k,subitem_index:e};var q=document.createTextNode(l=f.label);A.appendChild(q);return{mount:function(b,a){b.insertBefore(m,a)},update:function(b,a,d,c,k,f,e,h){g!==(g="menu-"+e.id)&&(m.id=g);n!==(n=e.type)&&(m.className=n);r!==(r="#"+e.id)&&(A.href=r);A._svelte.each_block_value_1=
f;A._svelte.subitem_index=h;l!==(l=e.label)&&(q.data=l)},unmount:function(){x(m)},destroy:function(){A.removeEventListener("click",z,!1)}}}function y(b,a,d,c,k){var g=document.createElement("ul");g.className="subsection";for(var f=d.children,e=[],l=0;l<f.length;l+=1)e[l]=m(b,a,d,c,f,f[l],l,k),e[l].mount(g,null);return{mount:function(a,b){a.insertBefore(g,b)},update:function(a,b,d,c,f){var h=c.children;if("menuItems"in a){for(var n=0;n<h.length;n+=1)e[n]?e[n].update(a,b,d,c,f,h,h[n],n):(e[n]=m(b,d,
c,f,h,h[n],n,k),e[n].mount(g,null));for(;n<e.length;n+=1)e[n].unmount(),e[n].destroy();e.length=h.length}},unmount:function(){x(g);for(var a=0;a<e.length;a+=1)e[a].unmount()},destroy:function(){h(e,!1,0)}}}function v(a){this._svelte.component.scrollToItem(this._svelte.each_block_value[this._svelte.item_index],a)}function z(a){this._svelte.component.scrollToItem(this._svelte.each_block_value_1[this._svelte.subitem_index],a)}function t(b){b=b||{};this.refs={};this._state=f(a.data(),b.data);this._observers=
{pre:Object.create(null),post:Object.create(null)};this._handlers=Object.create(null);this._root=b._root||this;this._yield=b._yield;this._torndown=!1;this._fragment=l(this._state,this);b.target&&this._fragment.mount(b.target,null);b._root?b._root._renderHooks.push(a.oncreate.bind(this)):a.oncreate.call(this)}function x(a){a.parentNode.removeChild(a)}function q(a,g){g.appendChild(a)}function h(a,g,d){for(;d<a.length;d+=1)a[d]&&a[d].destroy(g)}function f(a){for(var b,d,c=1,k=arguments.length;c<k;c++)for(b in d=
arguments[c],d)a[b]=d[b];return a}function u(a,c,d,f){for(var b in c)if(b in d){var g=d[b],e=f[b];if(g!==e||g&&"object"===typeof g||"function"===typeof g){var h=c[b];if(h)for(var l=0;l<h.length;l+=1){var m=h[l];m.__calling||(m.__calling=!0,m.call(a,g,e),m.__calling=!1)}}}}var a=function(){return{oncreate:function(){},data:function(){return{menuItems:[],menuItemsFlat:[],isOpen:!1,prevY:0}},methods:{onAppScroll:function(a){a=this.get("menuItemsFlat");a=$jscomp.makeIterator(a.entries());for(var b=a.next();!b.done;b=
a.next()){b=$jscomp.makeIterator(b.value);b.next();var b=b.next().value,d=document.getElementById(b.id),c=d.getBoundingClientRect().top,d=d.getBoundingClientRect().bottom;if(0<=c&&d<=window.innerHeight){[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu li.active"))).map(function(a){return a.classList.remove("active")});a=document.getElementById("menu-"+b.id);a.classList.add("active");b=a.parentNode;b.classList.contains("subsection")&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),
b.classList.add("show"));0<a.querySelectorAll(".subsection").length&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),a.querySelector(".subsection").classList.add("show"));break}}},startMenu:function(a){var b=this;this.set(a);setTimeout(function(){b.scrollToURLMenu()},10)},scrollTop:function(){window.scrollTo(0,0);this.close()},scrollToURLMenu:function(){var a=window.location.hash.substr(2),c=this.get("menuItemsFlat").filter(function(b){return b.id===
a});0<c.length?(c=document.getElementById(c[0].id),c=window.scrollY+c.getBoundingClientRect().top-70,window.scrollTo(0,c)):window.scrollTo(0,1)},toggle:function(){this.set({isOpen:!this.refs.menu.isOpen});return this.refs.menu.isOpen},close:function(){this.set({isOpen:!1})},open:function(){this.set({isOpen:!0})},scrollToItem:function(a,c){c&&c.preventDefault();window.location.hash="/"+a.id;this.get("menuItemsFlat");a=window.scrollY+document.getElementById(a.id).getBoundingClientRect().top-70;window.scrollTo(0,
a);this.fire("mobilemenu",{action:"CLOSE"})}}}}();f(t.prototype,a.methods,{get:function(a){return a?this._state[a]:this._state},fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var b=0;b<a.length;b+=1)a[b].call(this,c)},observe:function(a,c,d){var b=d&&d.defer?this._observers.post:this._observers.pre;(b[a]||(b[a]=[])).push(c);d&&!1===d.init||(c.__calling=!0,c.call(this,this._state[a]),c.__calling=!1);return{cancel:function(){var d=b[a].indexOf(c);~d&&b[a].splice(d,1)}}},
on:function(a,c){if("teardown"===a)return this.on("destroy",c);var b=this._handlers[a]||(this._handlers[a]=[]);b.push(c);return{cancel:function(){var a=b.indexOf(c);~a&&b.splice(a,1)}}},set:function(a){this._set(f({},a));this._root._flush()},_flush:function(){if(this._renderHooks)for(;this._renderHooks.length;)this._renderHooks.pop()()}});t.prototype._set=function(a){var b=this._state;this._state=f({},b,a);u(this,this._observers.pre,a,b);this._fragment.update(a,this._state);u(this,this._observers.post,
a,b)};t.prototype.teardown=t.prototype.destroy=function(a){this.fire("destroy");!1!==a&&this._fragment.unmount();this._fragment.destroy();this._fragment=null;this._state={};this._torndown=!0};p.exports=t});require.register("components/topbar.component.svelte",function(c,e,p){function l(a,c){function b(a){c.fire("mobilemenu",{action:"TOGGLE"})}var g,k=document.createElement("div");k.className="TopbarComp";var f=document.createElement("div");k.appendChild(f);f.className="menu-button";f.addEventListener("click",
b,!1);var e=z("svg");f.appendChild(e);t(e,"class",g="svg-icon "+(a.isMenuOpen?"off":""));e.setAttribute("xmlns","http://www.w3.org/2000/svg");e.setAttribute("role","img");e.setAttribute("viewBox","0 0 40 28");var h=z("use");e.appendChild(h);x(h,"xlink:href","img/icon-menu-open.svg#icon");h.setAttribute("preserveAspectRatio","xMidYMid");v(document.createTextNode("\n\n    "),k);var l=a.settings.allow_font_size_control&&w(a,c);l&&l.mount(k,null);var q=document.createTextNode("\n\n    ");k.appendChild(q);
var p=a.settings.allow_topbar_link&&m(a,c);p&&p.mount(k,null);return{mount:function(a,b){a.insertBefore(k,b)},update:function(a,b){g!==(g="svg-icon "+(b.isMenuOpen?"off":""))&&e.setAttribute("class",g);b.settings.allow_font_size_control?l||(l=w(b,c),l.mount(k,q)):l&&(l.unmount(),l.destroy(),l=null);b.settings.allow_topbar_link?p?p.update(a,b):(p=m(b,c),p.mount(k,null)):p&&(p.unmount(),p.destroy(),p=null)},unmount:function(){k.parentNode.removeChild(k);l&&l.unmount();p&&p.unmount()},destroy:function(){f.removeEventListener("click",
b,!1);l&&l.destroy();p&&p.destroy()}}}function w(a,c){function b(a){c.fire("fontsize",{action:"DECREASE"})}function g(a){c.fire("fontsize",{action:"INCREASE"})}var k=document.createElement("div");k.className="btn-group";var f=document.createElement("div");k.appendChild(f);f.className="btn btn-svg v-center";f.addEventListener("click",b,!1);a=z("svg");f.appendChild(a);a.setAttribute("class","svg-icon");a.setAttribute("xmlns","http://www.w3.org/2000/svg");a.setAttribute("role","img");a.setAttribute("viewBox",
"0 0 26 20");var e=z("use");a.appendChild(e);x(e,"xlink:href","img/icon-font-minus.svg#icon");e.setAttribute("preserveAspectRatio","xMidYMid");v(document.createTextNode("\n      "),k);var h=document.createElement("div");k.appendChild(h);h.className="btn btn-svg v-center";h.addEventListener("click",g,!1);a=z("svg");h.appendChild(a);a.setAttribute("class","svg-icon");a.setAttribute("xmlns","http://www.w3.org/2000/svg");a.setAttribute("role","img");a.setAttribute("viewBox","0 0 26 20");e=z("use");a.appendChild(e);
x(e,"xlink:href","img/icon-font-plus.svg#icon");e.setAttribute("preserveAspectRatio","xMidYMid");return{mount:function(a,b){a.insertBefore(k,b)},unmount:function(){k.parentNode.removeChild(k)},destroy:function(){f.removeEventListener("click",b,!1);h.removeEventListener("click",g,!1)}}}function m(a,c){var b,g,e=document.createElement("a");e.href=b=a.settings.topbar_link_url;e.className="btn btn-last-link";var h=document.createTextNode(g=a.settings.topbar_link_label);e.appendChild(h);return{mount:function(a,
b){a.insertBefore(e,b)},update:function(a,c){b!==(b=c.settings.topbar_link_url)&&(e.href=b);g!==(g=c.settings.topbar_link_label)&&(h.data=g)},unmount:function(){e.parentNode.removeChild(e)},destroy:f}}function y(b){b=b||{};this._state=q(a.data(),b.data);this._observers={pre:Object.create(null),post:Object.create(null)};this._handlers=Object.create(null);this._root=b._root||this;this._yield=b._yield;this._torndown=!1;this._fragment=l(this._state,this);b.target&&this._fragment.mount(b.target,null)}
function v(a,c){c.appendChild(a)}function z(a){return document.createElementNS("http://www.w3.org/2000/svg",a)}function t(a,c,d){a.setAttribute(c,d)}function x(a,c,d){a.setAttributeNS("http://www.w3.org/1999/xlink",c,d)}function q(a){for(var b,c,e=1,f=arguments.length;e<f;e++)for(b in c=arguments[e],c)a[b]=c[b];return a}function h(a,c,d,e){for(var b in c)if(b in d){var g=d[b],f=e[b];if(g!==f||g&&"object"===typeof g||"function"===typeof g){var h=c[b];if(h)for(var l=0;l<h.length;l+=1){var m=h[l];m.__calling||
(m.__calling=!0,m.call(a,g,f),m.__calling=!1)}}}}function f(){}var u=e("../herodotus-settings.js"),u=u&&u.__esModule?u["default"]:u,a=function(){return{data:function(){return{settings:u}}}}();q(y.prototype,{get:function(a){return a?this._state[a]:this._state},fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var b=0;b<a.length;b+=1)a[b].call(this,c)},observe:function(a,c,d){var b=d&&d.defer?this._observers.post:this._observers.pre;(b[a]||(b[a]=[])).push(c);d&&!1===d.init||
(c.__calling=!0,c.call(this,this._state[a]),c.__calling=!1);return{cancel:function(){var d=b[a].indexOf(c);~d&&b[a].splice(d,1)}}},on:function(a,c){if("teardown"===a)return this.on("destroy",c);var b=this._handlers[a]||(this._handlers[a]=[]);b.push(c);return{cancel:function(){var a=b.indexOf(c);~a&&b.splice(a,1)}}},set:function(a){this._set(q({},a));this._root._flush()},_flush:function(){if(this._renderHooks)for(;this._renderHooks.length;)this._renderHooks.pop()()}});y.prototype._set=function(a){var b=
this._state;this._state=q({},b,a);h(this,this._observers.pre,a,b);this._fragment.update(a,this._state);h(this,this._observers.post,a,b)};y.prototype.teardown=y.prototype.destroy=function(a){this.fire("destroy");!1!==a&&this._fragment.unmount();this._fragment.destroy();this._fragment=null;this._state={};this._torndown=!0};p.exports=y});require.register("herodotus-settings.js",function(c,e,p){Object.defineProperty(c,"__esModule",{value:!0});c.default={documentation_name:"My awesome documentation",allow_topbar_link:!0,
topbar_link_label:"Contribute to Peercoin Docs",topbar_link_url:"https://github.com/peercoin/docs#peercoin-official-documentation-repository",allow_font_size_control:!0,allow_remote_documentation:!1,remote_documentation_url:""}});require.register("initialize.js",function(c,e,p){var l=(c=e("./components/main.component"))&&c.__esModule?c:{default:c};document.addEventListener("DOMContentLoaded",function(){window.mainComponent=new l.default({target:document.querySelector("main")})})});require.alias("@fdaciuk/ajax/dist/ajax.min.js",
"@fdaciuk/ajax");require.alias("marked/lib/marked.js","marked");require.register("___globals___",function(c,e,p){})})();require("___globals___");require("initialize");